-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_classifier_ecg_classifier_Pipeline_L0_K_FILL is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln128 : IN STD_LOGIC_VECTOR (26 downto 0);
    sub_ln837 : IN STD_LOGIC_VECTOR (8 downto 0);
    add_ln113_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    t_5 : IN STD_LOGIC_VECTOR (6 downto 0);
    trunc_ln114_mid2 : IN STD_LOGIC_VECTOR (0 downto 0);
    norm_buf_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    norm_buf_V_ce0 : OUT STD_LOGIC;
    norm_buf_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    norm_buf_V_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    norm_buf_V_1_ce0 : OUT STD_LOGIC;
    norm_buf_V_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_V_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_V_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ecg_classifier_ecg_classifier_Pipeline_L0_K_FILL is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv9_BB : STD_LOGIC_VECTOR (8 downto 0) := "010111011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln130_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal L0_W_V_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal L0_W_V_0_ce0 : STD_LOGIC;
    signal L0_W_V_0_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln130_reg_452 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln130_reg_452_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln133_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln133_reg_461 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln134_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln134_reg_476 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln133_fu_321_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln133_reg_481 : STD_LOGIC_VECTOR (31 downto 0);
    signal L0_W_V_0_load_reg_486 : STD_LOGIC_VECTOR (6 downto 0);
    signal r_V_fu_350_p2 : STD_LOGIC_VECTOR (65 downto 0);
    signal r_V_reg_491 : STD_LOGIC_VECTOR (65 downto 0);
    signal trunc_ln1347_fu_356_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1347_reg_496 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln837_22_fu_232_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln134_fu_295_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_V_1_fu_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal lhs_V_fu_104 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln128_cast_fu_188_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal k_fu_108 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln130_fu_216_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_k_1 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln837_fu_222_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln837_fu_226_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln132_fu_241_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln132_fu_247_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp5_fu_257_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln133_fu_269_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln133_fu_265_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln133_fu_273_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln132_1_fu_251_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln4_fu_285_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln132_fu_237_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_V_fu_312_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_8_fu_328_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal shl_ln838_2_fu_335_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln1347_2_fu_374_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal lhs_V_4_fu_363_p3 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1347_fu_371_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal trunc_ln1347_1_fu_378_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ret_V_fu_386_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln1347_1_fu_392_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_classifier_mux_21_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_classifier_mul_27s_40s_66_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (26 downto 0);
        din1 : IN STD_LOGIC_VECTOR (39 downto 0);
        dout : OUT STD_LOGIC_VECTOR (65 downto 0) );
    end component;


    component ecg_classifier_ecg_classifier_Pipeline_L0_K_FILL_L0_W_V_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component ecg_classifier_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    L0_W_V_0_U : component ecg_classifier_ecg_classifier_Pipeline_L0_K_FILL_L0_W_V_0_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 448,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => L0_W_V_0_address0,
        ce0 => L0_W_V_0_ce0,
        q0 => L0_W_V_0_q0);

    mux_21_32_1_1_U31 : component ecg_classifier_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => norm_buf_V_1_q0,
        din1 => norm_buf_V_q0,
        din2 => xor_ln134_reg_476,
        dout => x_V_fu_312_p4);

    mul_27s_40s_66_1_1_U32 : component ecg_classifier_mul_27s_40s_66_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 27,
        din1_WIDTH => 40,
        dout_WIDTH => 66)
    port map (
        din0 => shl_ln838_2_fu_335_p3,
        din1 => r_V_8_fu_328_p3,
        dout => r_V_fu_350_p2);

    flow_control_loop_pipe_sequential_init_U : component ecg_classifier_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    k_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln130_fu_210_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_108 <= add_ln130_fu_216_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_108 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_V_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    lhs_V_fu_104 <= sext_ln128_cast_fu_188_p1;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    lhs_V_fu_104 <= ret_V_fu_386_p2(71 downto 24);
                end if;
            end if; 
        end if;
    end process;

    x_V_1_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    x_V_1_fu_100 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    x_V_1_fu_100 <= add_ln1347_1_fu_392_p2(63 downto 32);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                L0_W_V_0_load_reg_486 <= L0_W_V_0_q0;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln130_reg_452 <= icmp_ln130_fu_210_p2;
                icmp_ln130_reg_452_pp0_iter1_reg <= icmp_ln130_reg_452;
                select_ln133_reg_481 <= select_ln133_fu_321_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln130_fu_210_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln133_reg_461 <= icmp_ln133_fu_279_p2;
                xor_ln134_reg_476 <= xor_ln134_fu_301_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                r_V_reg_491 <= r_V_fu_350_p2;
                trunc_ln1347_reg_496 <= trunc_ln1347_fu_356_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    L0_W_V_0_address0 <= zext_ln837_22_fu_232_p1(9 - 1 downto 0);

    L0_W_V_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            L0_W_V_0_ce0 <= ap_const_logic_1;
        else 
            L0_W_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln130_fu_216_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_1) + unsigned(ap_const_lv3_1));
    add_ln132_1_fu_251_p2 <= std_logic_vector(signed(sext_ln132_fu_247_p1) + signed(add_ln113_1));
    add_ln132_fu_241_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_1) + unsigned(ap_const_lv3_5));
    add_ln133_fu_273_p2 <= std_logic_vector(signed(sext_ln133_fu_269_p1) + signed(zext_ln133_fu_265_p1));
    add_ln1347_1_fu_392_p2 <= std_logic_vector(unsigned(trunc_ln1347_1_fu_378_p3) + unsigned(trunc_ln1347_reg_496));
    add_ln837_fu_226_p2 <= std_logic_vector(unsigned(sub_ln837) + unsigned(zext_ln837_fu_222_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln130_fu_210_p2)
    begin
        if (((icmp_ln130_fu_210_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_108)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_k_1 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_k_1 <= k_fu_108;
        end if; 
    end process;

    icmp_ln130_fu_210_p2 <= "1" when (ap_sig_allocacmp_k_1 = ap_const_lv3_7) else "0";
    icmp_ln133_fu_279_p2 <= "1" when (unsigned(add_ln133_fu_273_p2) < unsigned(ap_const_lv9_BB)) else "0";
    lhs_V_4_fu_363_p3 <= (lhs_V_fu_104 & ap_const_lv24_0);
    lshr_ln4_fu_285_p4 <= add_ln132_1_fu_251_p2(7 downto 1);
    norm_buf_V_1_address0 <= zext_ln134_fu_295_p1(7 - 1 downto 0);

    norm_buf_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            norm_buf_V_1_ce0 <= ap_const_logic_1;
        else 
            norm_buf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    norm_buf_V_address0 <= zext_ln134_fu_295_p1(7 - 1 downto 0);

    norm_buf_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            norm_buf_V_ce0 <= ap_const_logic_1;
        else 
            norm_buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    r_V_8_fu_328_p3 <= (select_ln133_reg_481 & ap_const_lv8_0);
    ret_V_fu_386_p2 <= std_logic_vector(unsigned(lhs_V_4_fu_363_p3) + unsigned(sext_ln1347_fu_371_p1));
    select_ln133_fu_321_p3 <= 
        x_V_fu_312_p4 when (icmp_ln133_reg_461(0) = '1') else 
        ap_const_lv32_0;
        sext_ln128_cast_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln128),48));

        sext_ln132_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln132_fu_241_p2),8));

        sext_ln133_fu_269_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln132_fu_241_p2),9));

        sext_ln1347_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_reg_491),72));

    shl_ln838_2_fu_335_p3 <= (L0_W_V_0_load_reg_486 & ap_const_lv20_0);
    tmp5_fu_257_p3 <= (t_5 & trunc_ln114_mid2);
    trunc_ln132_fu_237_p1 <= ap_sig_allocacmp_k_1(1 - 1 downto 0);
    trunc_ln1347_1_fu_378_p3 <= (trunc_ln1347_2_fu_374_p1 & ap_const_lv24_0);
    trunc_ln1347_2_fu_374_p1 <= lhs_V_fu_104(40 - 1 downto 0);
    trunc_ln1347_fu_356_p1 <= r_V_fu_350_p2(64 - 1 downto 0);
    x_V_1_out <= x_V_1_fu_100;

    x_V_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln130_reg_452_pp0_iter1_reg)
    begin
        if (((icmp_ln130_reg_452_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            x_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            x_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln134_fu_301_p2 <= (trunc_ln132_fu_237_p1 xor trunc_ln114_mid2);
    zext_ln133_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp5_fu_257_p3),9));
    zext_ln134_fu_295_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln4_fu_285_p4),64));
    zext_ln837_22_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln837_fu_226_p2),64));
    zext_ln837_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k_1),9));
end behav;
