-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_denoiser_conv_layer01234_fused_Pipeline_L0_K is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln77 : IN STD_LOGIC_VECTOR (23 downto 0);
    phi_mul : IN STD_LOGIC_VECTOR (9 downto 0);
    add_ln81 : IN STD_LOGIC_VECTOR (8 downto 0);
    add_ln82_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    in_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    in_0_ce0 : OUT STD_LOGIC;
    in_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    in_1_ce0 : OUT STD_LOGIC;
    in_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    trunc_ln : IN STD_LOGIC_VECTOR (0 downto 0);
    x_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_V_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ecg_denoiser_conv_layer01234_fused_Pipeline_L0_K is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv10_168 : STD_LOGIC_VECTOR (9 downto 0) := "0101101000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln79_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal denoiser_w_L0_W_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal denoiser_w_L0_W_V_ce0 : STD_LOGIC;
    signal denoiser_w_L0_W_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal k_1_reg_437 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln79_reg_443 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln79_reg_443_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln82_fu_289_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln82_reg_462 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_13_fu_320_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal r_V_13_reg_467 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln82_fu_236_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln837_22_fu_255_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_V_fu_94 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal lhs_fu_98 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln77_cast_fu_182_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal k_fu_102 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln79_fu_210_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_k_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln79_fu_216_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln81_1_fu_220_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln3_fu_226_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln837_fu_247_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln837_fu_250_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln82_fu_263_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln81_fu_260_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_V_1_fu_279_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_V_1_fu_279_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_fu_297_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal shl_ln838_1_fu_304_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln1347_fu_343_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal lhs_1_fu_329_p3 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1347_fu_337_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal trunc_ln1_fu_347_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln1347_1_fu_340_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ret_V_fu_355_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln1347_1_fu_361_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_denoiser_mux_21_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_denoiser_mul_24s_40s_63_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (39 downto 0);
        dout : OUT STD_LOGIC_VECTOR (62 downto 0) );
    end component;


    component ecg_denoiser_conv_layer01234_fused_Pipeline_L0_K_denoiser_w_L0_W_V_ROM_NP_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component ecg_denoiser_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    denoiser_w_L0_W_V_U : component ecg_denoiser_conv_layer01234_fused_Pipeline_L0_K_denoiser_w_L0_W_V_ROM_NP_LUTRAM_1R
    generic map (
        DataWidth => 16,
        AddressRange => 704,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => denoiser_w_L0_W_V_address0,
        ce0 => denoiser_w_L0_W_V_ce0,
        q0 => denoiser_w_L0_W_V_q0);

    mux_21_32_1_1_U31 : component ecg_denoiser_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => in_1_q0,
        din1 => in_0_q0,
        din2 => x_V_1_fu_279_p3,
        dout => x_V_1_fu_279_p4);

    mul_24s_40s_63_1_1_U32 : component ecg_denoiser_mul_24s_40s_63_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 40,
        dout_WIDTH => 63)
    port map (
        din0 => shl_ln838_1_fu_304_p3,
        din1 => r_V_fu_297_p3,
        dout => r_V_13_fu_320_p2);

    flow_control_loop_pipe_sequential_init_U : component ecg_denoiser_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    k_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln79_fu_204_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_102 <= add_ln79_fu_210_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_102 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    lhs_fu_98 <= sext_ln77_cast_fu_182_p1;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    lhs_fu_98 <= ret_V_fu_355_p2(71 downto 24);
                end if;
            end if; 
        end if;
    end process;

    x_V_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    x_V_fu_94 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    x_V_fu_94 <= add_ln1347_1_fu_361_p2(63 downto 32);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln79_reg_443 <= icmp_ln79_fu_204_p2;
                icmp_ln79_reg_443_pp0_iter1_reg <= icmp_ln79_reg_443;
                k_1_reg_437 <= ap_sig_allocacmp_k_1;
                select_ln82_reg_462 <= select_ln82_fu_289_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                r_V_13_reg_467 <= r_V_13_fu_320_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1347_1_fu_361_p2 <= std_logic_vector(unsigned(trunc_ln1_fu_347_p3) + unsigned(sext_ln1347_1_fu_340_p1));
    add_ln79_fu_210_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_1) + unsigned(ap_const_lv4_1));
    add_ln81_1_fu_220_p2 <= std_logic_vector(unsigned(add_ln81) + unsigned(zext_ln79_fu_216_p1));
    add_ln82_fu_263_p2 <= std_logic_vector(unsigned(add_ln82_1) + unsigned(zext_ln837_fu_247_p1));
    add_ln837_fu_250_p2 <= std_logic_vector(unsigned(phi_mul) + unsigned(zext_ln837_fu_247_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln79_fu_204_p2)
    begin
        if (((icmp_ln79_fu_204_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_102)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_k_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_k_1 <= k_fu_102;
        end if; 
    end process;

    denoiser_w_L0_W_V_address0 <= zext_ln837_22_fu_255_p1(10 - 1 downto 0);

    denoiser_w_L0_W_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            denoiser_w_L0_W_V_ce0 <= ap_const_logic_1;
        else 
            denoiser_w_L0_W_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln79_fu_204_p2 <= "1" when (ap_sig_allocacmp_k_1 = ap_const_lv4_B) else "0";
    icmp_ln82_fu_268_p2 <= "1" when (unsigned(add_ln82_fu_263_p2) < unsigned(ap_const_lv10_168)) else "0";
    in_0_address0 <= zext_ln82_fu_236_p1(8 - 1 downto 0);

    in_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_0_ce0 <= ap_const_logic_1;
        else 
            in_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in_1_address0 <= zext_ln82_fu_236_p1(8 - 1 downto 0);

    in_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_1_ce0 <= ap_const_logic_1;
        else 
            in_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    lhs_1_fu_329_p3 <= (lhs_fu_98 & ap_const_lv24_0);
    lshr_ln3_fu_226_p4 <= add_ln81_1_fu_220_p2(8 downto 1);
    r_V_fu_297_p3 <= (select_ln82_reg_462 & ap_const_lv8_0);
    ret_V_fu_355_p2 <= std_logic_vector(unsigned(lhs_1_fu_329_p3) + unsigned(sext_ln1347_fu_337_p1));
    select_ln82_fu_289_p3 <= 
        x_V_1_fu_279_p4 when (icmp_ln82_fu_268_p2(0) = '1') else 
        ap_const_lv32_0;
        sext_ln1347_1_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_13_reg_467),64));

        sext_ln1347_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_13_reg_467),72));

        sext_ln77_cast_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln77),48));

    shl_ln838_1_fu_304_p3 <= (denoiser_w_L0_W_V_q0 & ap_const_lv8_0);
    trunc_ln1347_fu_343_p1 <= lhs_fu_98(40 - 1 downto 0);
    trunc_ln1_fu_347_p3 <= (trunc_ln1347_fu_343_p1 & ap_const_lv24_0);
    trunc_ln81_fu_260_p1 <= k_1_reg_437(1 - 1 downto 0);
    x_V_1_fu_279_p3 <= (trunc_ln81_fu_260_p1 xor trunc_ln);
    x_V_out <= x_V_fu_94;

    x_V_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln79_reg_443_pp0_iter1_reg)
    begin
        if (((icmp_ln79_reg_443_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            x_V_out_ap_vld <= ap_const_logic_1;
        else 
            x_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln79_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k_1),9));
    zext_ln82_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln3_fu_226_p4),64));
    zext_ln837_22_fu_255_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln837_fu_250_p2),64));
    zext_ln837_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_1_reg_437),10));
end behav;
