-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_denoiser_conv_layer01234_fused_Pipeline_L4_IC_L4_K is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    win34_V_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_2_ce0 : OUT STD_LOGIC;
    win34_V_2_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_2_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_2_ce1 : OUT STD_LOGIC;
    win34_V_2_q1 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_3_ce0 : OUT STD_LOGIC;
    win34_V_3_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_3_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_3_ce1 : OUT STD_LOGIC;
    win34_V_3_q1 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_4_ce0 : OUT STD_LOGIC;
    win34_V_4_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_4_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_4_ce1 : OUT STD_LOGIC;
    win34_V_4_q1 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_5_ce0 : OUT STD_LOGIC;
    win34_V_5_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_5_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_5_ce1 : OUT STD_LOGIC;
    win34_V_5_q1 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_6_ce0 : OUT STD_LOGIC;
    win34_V_6_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_6_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_6_ce1 : OUT STD_LOGIC;
    win34_V_6_q1 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_7_ce0 : OUT STD_LOGIC;
    win34_V_7_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_7_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_7_ce1 : OUT STD_LOGIC;
    win34_V_7_q1 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_8_ce0 : OUT STD_LOGIC;
    win34_V_8_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_8_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_8_ce1 : OUT STD_LOGIC;
    win34_V_8_q1 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_9_ce0 : OUT STD_LOGIC;
    win34_V_9_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_9_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_9_ce1 : OUT STD_LOGIC;
    win34_V_9_q1 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_10_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_10_ce0 : OUT STD_LOGIC;
    win34_V_10_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_10_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_10_ce1 : OUT STD_LOGIC;
    win34_V_10_q1 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_11_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_11_ce0 : OUT STD_LOGIC;
    win34_V_11_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    win34_V_11_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    win34_V_11_ce1 : OUT STD_LOGIC;
    win34_V_11_q1 : IN STD_LOGIC_VECTOR (30 downto 0);
    phi_ln818_6_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    phi_ln818_6_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ecg_denoiser_conv_layer01234_fused_Pipeline_L4_IC_L4_K is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv48_FFFFFFFF3A00 : STD_LOGIC_VECTOR (47 downto 0) := "111111111111111111111111111111110011101000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv8_E0 : STD_LOGIC_VECTOR (7 downto 0) := "11100000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln212_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal denoiser_w_L4_W_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal denoiser_w_L4_W_V_ce0 : STD_LOGIC;
    signal denoiser_w_L4_W_V_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal empty_fu_453_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_942 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln212_reg_1003 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln212_reg_1003_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln214_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln214_reg_1007 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln212_fu_484_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln212_reg_1018 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_54_fu_546_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_54_reg_1023 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln837_fu_554_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln837_reg_1084 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_V_fu_784_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_V_reg_1094 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_5_fu_826_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal r_V_5_reg_1099 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal p_cast22_fu_439_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_cast22_mid1_fu_532_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln837_2_fu_780_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_ln818_6_fu_108 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal lhs_fu_112 : STD_LOGIC_VECTOR (47 downto 0);
    signal k_fu_116 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln214_fu_560_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_k_load : STD_LOGIC_VECTOR (2 downto 0);
    signal ic_fu_120 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln212_1_fu_492_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_ic_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten72_fu_124 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln212_1_fu_463_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten72_load : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_s_fu_429_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln212_fu_472_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln212_fu_500_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_8_fu_508_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln837_fu_504_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_mid1_fu_522_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln837_fu_516_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln837_1_fu_550_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_mid1_fu_644_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_581_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_mid1_fu_660_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_1_fu_590_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln212_3_fu_669_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_13_mid1_fu_680_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_2_fu_599_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln212_4_fu_689_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_14_mid1_fu_700_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_3_fu_608_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln212_5_fu_709_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_15_mid1_fu_720_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_4_fu_617_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln212_6_fu_729_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_16_mid1_fu_740_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_6_fu_626_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln212_7_fu_749_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_17_mid1_fu_760_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_7_fu_635_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln212_8_fu_769_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal x_V_fu_784_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_V_fu_784_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_V_fu_784_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_V_fu_784_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_V_fu_784_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_V_fu_784_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_V_fu_784_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_fu_803_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal shl_ln838_6_fu_810_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln214_fu_843_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln1347_s_fu_847_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln214_fu_855_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_1_fu_835_p3 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1347_fu_858_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln1347_fu_867_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln214_1_fu_861_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_denoiser_mux_21_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_denoiser_mux_21_31_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (30 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component ecg_denoiser_mux_73_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_denoiser_mul_23s_40s_62_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (22 downto 0);
        din1 : IN STD_LOGIC_VECTOR (39 downto 0);
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component ecg_denoiser_conv_layer01234_fused_Pipeline_L4_IC_L4_K_denoiser_w_L4_W_V_ROM_NP_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component ecg_denoiser_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    denoiser_w_L4_W_V_U : component ecg_denoiser_conv_layer01234_fused_Pipeline_L4_IC_L4_K_denoiser_w_L4_W_V_ROM_NP_LUTRAM_1R
    generic map (
        DataWidth => 15,
        AddressRange => 224,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => denoiser_w_L4_W_V_address0,
        ce0 => denoiser_w_L4_W_V_ce0,
        q0 => denoiser_w_L4_W_V_q0);

    mux_21_32_1_1_U97 : component ecg_denoiser_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_0,
        din1 => ap_const_lv32_0,
        din2 => empty_reg_942,
        dout => tmp_5_fu_581_p4);

    mux_21_31_1_1_U98 : component ecg_denoiser_mux_21_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        din2_WIDTH => 1,
        dout_WIDTH => 31)
    port map (
        din0 => ap_const_lv31_0,
        din1 => ap_const_lv31_0,
        din2 => empty_reg_942,
        dout => tmp_1_fu_590_p4);

    mux_21_31_1_1_U99 : component ecg_denoiser_mux_21_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        din2_WIDTH => 1,
        dout_WIDTH => 31)
    port map (
        din0 => win34_V_2_q1,
        din1 => win34_V_3_q1,
        din2 => empty_reg_942,
        dout => tmp_2_fu_599_p4);

    mux_21_31_1_1_U100 : component ecg_denoiser_mux_21_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        din2_WIDTH => 1,
        dout_WIDTH => 31)
    port map (
        din0 => win34_V_4_q1,
        din1 => win34_V_5_q1,
        din2 => empty_reg_942,
        dout => tmp_3_fu_608_p4);

    mux_21_31_1_1_U101 : component ecg_denoiser_mux_21_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        din2_WIDTH => 1,
        dout_WIDTH => 31)
    port map (
        din0 => win34_V_6_q1,
        din1 => win34_V_7_q1,
        din2 => empty_reg_942,
        dout => tmp_4_fu_617_p4);

    mux_21_31_1_1_U102 : component ecg_denoiser_mux_21_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        din2_WIDTH => 1,
        dout_WIDTH => 31)
    port map (
        din0 => win34_V_8_q1,
        din1 => win34_V_9_q1,
        din2 => empty_reg_942,
        dout => tmp_6_fu_626_p4);

    mux_21_31_1_1_U103 : component ecg_denoiser_mux_21_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        din2_WIDTH => 1,
        dout_WIDTH => 31)
    port map (
        din0 => win34_V_10_q1,
        din1 => win34_V_11_q1,
        din2 => empty_reg_942,
        dout => tmp_7_fu_635_p4);

    mux_21_32_1_1_U104 : component ecg_denoiser_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_0,
        din1 => ap_const_lv32_0,
        din2 => empty_54_reg_1023,
        dout => tmp_5_mid1_fu_644_p4);

    mux_21_31_1_1_U105 : component ecg_denoiser_mux_21_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        din2_WIDTH => 1,
        dout_WIDTH => 31)
    port map (
        din0 => ap_const_lv31_0,
        din1 => ap_const_lv31_0,
        din2 => empty_54_reg_1023,
        dout => tmp_12_mid1_fu_660_p4);

    mux_21_31_1_1_U106 : component ecg_denoiser_mux_21_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        din2_WIDTH => 1,
        dout_WIDTH => 31)
    port map (
        din0 => win34_V_2_q0,
        din1 => win34_V_3_q0,
        din2 => empty_54_reg_1023,
        dout => tmp_13_mid1_fu_680_p4);

    mux_21_31_1_1_U107 : component ecg_denoiser_mux_21_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        din2_WIDTH => 1,
        dout_WIDTH => 31)
    port map (
        din0 => win34_V_4_q0,
        din1 => win34_V_5_q0,
        din2 => empty_54_reg_1023,
        dout => tmp_14_mid1_fu_700_p4);

    mux_21_31_1_1_U108 : component ecg_denoiser_mux_21_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        din2_WIDTH => 1,
        dout_WIDTH => 31)
    port map (
        din0 => win34_V_6_q0,
        din1 => win34_V_7_q0,
        din2 => empty_54_reg_1023,
        dout => tmp_15_mid1_fu_720_p4);

    mux_21_31_1_1_U109 : component ecg_denoiser_mux_21_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        din2_WIDTH => 1,
        dout_WIDTH => 31)
    port map (
        din0 => win34_V_8_q0,
        din1 => win34_V_9_q0,
        din2 => empty_54_reg_1023,
        dout => tmp_16_mid1_fu_740_p4);

    mux_21_31_1_1_U110 : component ecg_denoiser_mux_21_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        din2_WIDTH => 1,
        dout_WIDTH => 31)
    port map (
        din0 => win34_V_10_q0,
        din1 => win34_V_11_q0,
        din2 => empty_54_reg_1023,
        dout => tmp_17_mid1_fu_760_p4);

    mux_73_32_1_1_U111 : component ecg_denoiser_mux_73_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => x_V_fu_784_p1,
        din1 => x_V_fu_784_p2,
        din2 => x_V_fu_784_p3,
        din3 => x_V_fu_784_p4,
        din4 => x_V_fu_784_p5,
        din5 => x_V_fu_784_p6,
        din6 => x_V_fu_784_p7,
        din7 => select_ln212_reg_1018,
        dout => x_V_fu_784_p9);

    mul_23s_40s_62_1_1_U112 : component ecg_denoiser_mul_23s_40s_62_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 23,
        din1_WIDTH => 40,
        dout_WIDTH => 62)
    port map (
        din0 => shl_ln838_6_fu_810_p3,
        din1 => r_V_fu_803_p3,
        dout => r_V_5_fu_826_p2);

    flow_control_loop_pipe_sequential_init_U : component ecg_denoiser_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ic_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln212_fu_457_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    ic_fu_120 <= select_ln212_1_fu_492_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ic_fu_120 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten72_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln212_fu_457_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten72_fu_124 <= add_ln212_1_fu_463_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten72_fu_124 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    k_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln212_fu_457_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_116 <= add_ln214_fu_560_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_116 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    lhs_fu_112 <= ap_const_lv48_FFFFFFFF3A00;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    lhs_fu_112 <= add_ln1347_fu_867_p2(71 downto 24);
                end if;
            end if; 
        end if;
    end process;

    phi_ln818_6_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    phi_ln818_6_fu_108 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    phi_ln818_6_fu_108 <= add_ln214_1_fu_861_p2(63 downto 32);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln212_fu_457_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln837_reg_1084 <= add_ln837_fu_554_p2;
                empty_54_reg_1023 <= empty_54_fu_546_p1;
                icmp_ln214_reg_1007 <= icmp_ln214_fu_478_p2;
                select_ln212_reg_1018 <= select_ln212_fu_484_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                empty_reg_942 <= empty_fu_453_p1;
                icmp_ln212_reg_1003 <= icmp_ln212_fu_457_p2;
                icmp_ln212_reg_1003_pp0_iter1_reg <= icmp_ln212_reg_1003;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                r_V_5_reg_1099 <= r_V_5_fu_826_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln212_reg_1003 = ap_const_lv1_0))) then
                x_V_reg_1094 <= x_V_fu_784_p9;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1347_fu_867_p2 <= std_logic_vector(unsigned(lhs_1_fu_835_p3) + unsigned(sext_ln1347_fu_858_p1));
    add_ln212_1_fu_463_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten72_load) + unsigned(ap_const_lv8_1));
    add_ln212_fu_472_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ic_1) + unsigned(ap_const_lv6_1));
    add_ln214_1_fu_861_p2 <= std_logic_vector(unsigned(sext_ln1347_s_fu_847_p3) + unsigned(sext_ln214_fu_855_p1));
    add_ln214_fu_560_p2 <= std_logic_vector(unsigned(select_ln212_fu_484_p3) + unsigned(ap_const_lv3_1));
    add_ln837_fu_554_p2 <= std_logic_vector(unsigned(sub_ln837_fu_516_p2) + unsigned(zext_ln837_1_fu_550_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln212_fu_457_p2)
    begin
        if (((icmp_ln212_fu_457_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln212_reg_1003)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln212_reg_1003 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_ic_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, ic_fu_120)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_ic_1 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_ic_1 <= ic_fu_120;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten72_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten72_fu_124)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten72_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten72_load <= indvar_flatten72_fu_124;
        end if; 
    end process;


    ap_sig_allocacmp_k_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_116)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_k_load <= k_fu_116;
        end if; 
    end process;

    denoiser_w_L4_W_V_address0 <= zext_ln837_2_fu_780_p1(8 - 1 downto 0);

    denoiser_w_L4_W_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            denoiser_w_L4_W_V_ce0 <= ap_const_logic_1;
        else 
            denoiser_w_L4_W_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    empty_54_fu_546_p1 <= add_ln212_fu_472_p2(1 - 1 downto 0);
    empty_fu_453_p1 <= ap_sig_allocacmp_ic_1(1 - 1 downto 0);
    icmp_ln212_fu_457_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten72_load = ap_const_lv8_E0) else "0";
    icmp_ln214_fu_478_p2 <= "1" when (ap_sig_allocacmp_k_load = ap_const_lv3_7) else "0";
    lhs_1_fu_835_p3 <= (lhs_fu_112 & ap_const_lv24_0);
    p_cast22_fu_439_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_429_p4),64));
    p_cast22_mid1_fu_532_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid1_fu_522_p4),64));
    p_mid1_fu_522_p4 <= add_ln212_fu_472_p2(4 downto 1);
    phi_ln818_6_out <= phi_ln818_6_fu_108;

    phi_ln818_6_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln212_reg_1003_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln212_reg_1003_pp0_iter1_reg = ap_const_lv1_1))) then 
            phi_ln818_6_out_ap_vld <= ap_const_logic_1;
        else 
            phi_ln818_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    r_V_fu_803_p3 <= (x_V_reg_1094 & ap_const_lv8_0);
    select_ln212_1_fu_492_p3 <= 
        add_ln212_fu_472_p2 when (icmp_ln214_fu_478_p2(0) = '1') else 
        ap_sig_allocacmp_ic_1;
    select_ln212_3_fu_669_p3 <= 
        tmp_12_mid1_fu_660_p4 when (icmp_ln214_reg_1007(0) = '1') else 
        tmp_1_fu_590_p4;
    select_ln212_4_fu_689_p3 <= 
        tmp_13_mid1_fu_680_p4 when (icmp_ln214_reg_1007(0) = '1') else 
        tmp_2_fu_599_p4;
    select_ln212_5_fu_709_p3 <= 
        tmp_14_mid1_fu_700_p4 when (icmp_ln214_reg_1007(0) = '1') else 
        tmp_3_fu_608_p4;
    select_ln212_6_fu_729_p3 <= 
        tmp_15_mid1_fu_720_p4 when (icmp_ln214_reg_1007(0) = '1') else 
        tmp_4_fu_617_p4;
    select_ln212_7_fu_749_p3 <= 
        tmp_16_mid1_fu_740_p4 when (icmp_ln214_reg_1007(0) = '1') else 
        tmp_6_fu_626_p4;
    select_ln212_8_fu_769_p3 <= 
        tmp_17_mid1_fu_760_p4 when (icmp_ln214_reg_1007(0) = '1') else 
        tmp_7_fu_635_p4;
    select_ln212_fu_484_p3 <= 
        ap_const_lv3_0 when (icmp_ln214_fu_478_p2(0) = '1') else 
        ap_sig_allocacmp_k_load;
        sext_ln1347_fu_858_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_5_reg_1099),72));

    sext_ln1347_s_fu_847_p3 <= (trunc_ln214_fu_843_p1 & ap_const_lv24_0);
        sext_ln214_fu_855_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_5_reg_1099),64));

    shl_ln838_6_fu_810_p3 <= (denoiser_w_L4_W_V_q0 & ap_const_lv8_0);
    sub_ln837_fu_516_p2 <= std_logic_vector(unsigned(tmp_8_fu_508_p3) - unsigned(zext_ln837_fu_504_p1));
    tmp_8_fu_508_p3 <= (trunc_ln212_fu_500_p1 & ap_const_lv3_0);
    tmp_s_fu_429_p4 <= ap_sig_allocacmp_ic_1(4 downto 1);
    trunc_ln212_fu_500_p1 <= select_ln212_1_fu_492_p3(5 - 1 downto 0);
    trunc_ln214_fu_843_p1 <= lhs_fu_112(40 - 1 downto 0);
    win34_V_10_address0 <= p_cast22_mid1_fu_532_p1(4 - 1 downto 0);
    win34_V_10_address1 <= p_cast22_fu_439_p1(4 - 1 downto 0);

    win34_V_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_10_ce0 <= ap_const_logic_1;
        else 
            win34_V_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win34_V_10_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_10_ce1 <= ap_const_logic_1;
        else 
            win34_V_10_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    win34_V_11_address0 <= p_cast22_mid1_fu_532_p1(4 - 1 downto 0);
    win34_V_11_address1 <= p_cast22_fu_439_p1(4 - 1 downto 0);

    win34_V_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_11_ce0 <= ap_const_logic_1;
        else 
            win34_V_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win34_V_11_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_11_ce1 <= ap_const_logic_1;
        else 
            win34_V_11_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    win34_V_2_address0 <= p_cast22_mid1_fu_532_p1(4 - 1 downto 0);
    win34_V_2_address1 <= p_cast22_fu_439_p1(4 - 1 downto 0);

    win34_V_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_2_ce0 <= ap_const_logic_1;
        else 
            win34_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win34_V_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_2_ce1 <= ap_const_logic_1;
        else 
            win34_V_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    win34_V_3_address0 <= p_cast22_mid1_fu_532_p1(4 - 1 downto 0);
    win34_V_3_address1 <= p_cast22_fu_439_p1(4 - 1 downto 0);

    win34_V_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_3_ce0 <= ap_const_logic_1;
        else 
            win34_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win34_V_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_3_ce1 <= ap_const_logic_1;
        else 
            win34_V_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    win34_V_4_address0 <= p_cast22_mid1_fu_532_p1(4 - 1 downto 0);
    win34_V_4_address1 <= p_cast22_fu_439_p1(4 - 1 downto 0);

    win34_V_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_4_ce0 <= ap_const_logic_1;
        else 
            win34_V_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win34_V_4_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_4_ce1 <= ap_const_logic_1;
        else 
            win34_V_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    win34_V_5_address0 <= p_cast22_mid1_fu_532_p1(4 - 1 downto 0);
    win34_V_5_address1 <= p_cast22_fu_439_p1(4 - 1 downto 0);

    win34_V_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_5_ce0 <= ap_const_logic_1;
        else 
            win34_V_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win34_V_5_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_5_ce1 <= ap_const_logic_1;
        else 
            win34_V_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    win34_V_6_address0 <= p_cast22_mid1_fu_532_p1(4 - 1 downto 0);
    win34_V_6_address1 <= p_cast22_fu_439_p1(4 - 1 downto 0);

    win34_V_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_6_ce0 <= ap_const_logic_1;
        else 
            win34_V_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win34_V_6_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_6_ce1 <= ap_const_logic_1;
        else 
            win34_V_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    win34_V_7_address0 <= p_cast22_mid1_fu_532_p1(4 - 1 downto 0);
    win34_V_7_address1 <= p_cast22_fu_439_p1(4 - 1 downto 0);

    win34_V_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_7_ce0 <= ap_const_logic_1;
        else 
            win34_V_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win34_V_7_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_7_ce1 <= ap_const_logic_1;
        else 
            win34_V_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    win34_V_8_address0 <= p_cast22_mid1_fu_532_p1(4 - 1 downto 0);
    win34_V_8_address1 <= p_cast22_fu_439_p1(4 - 1 downto 0);

    win34_V_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_8_ce0 <= ap_const_logic_1;
        else 
            win34_V_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win34_V_8_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_8_ce1 <= ap_const_logic_1;
        else 
            win34_V_8_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    win34_V_9_address0 <= p_cast22_mid1_fu_532_p1(4 - 1 downto 0);
    win34_V_9_address1 <= p_cast22_fu_439_p1(4 - 1 downto 0);

    win34_V_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_9_ce0 <= ap_const_logic_1;
        else 
            win34_V_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win34_V_9_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win34_V_9_ce1 <= ap_const_logic_1;
        else 
            win34_V_9_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    x_V_fu_784_p1 <= 
        tmp_5_mid1_fu_644_p4 when (icmp_ln214_reg_1007(0) = '1') else 
        tmp_5_fu_581_p4;
    x_V_fu_784_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln212_3_fu_669_p3),32));
    x_V_fu_784_p3 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln212_4_fu_689_p3),32));
    x_V_fu_784_p4 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln212_5_fu_709_p3),32));
    x_V_fu_784_p5 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln212_6_fu_729_p3),32));
    x_V_fu_784_p6 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln212_7_fu_749_p3),32));
    x_V_fu_784_p7 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln212_8_fu_769_p3),32));
    zext_ln837_1_fu_550_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln212_fu_484_p3),8));
    zext_ln837_2_fu_780_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln837_reg_1084),64));
    zext_ln837_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln212_1_fu_492_p3),8));
end behav;
