-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_classifier_ecg_classifier_Pipeline_L3_IC_L3_K is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln226 : IN STD_LOGIC_VECTOR (25 downto 0);
    sext_ln225 : IN STD_LOGIC_VECTOR (25 downto 0);
    oc_base : IN STD_LOGIC_VECTOR (6 downto 0);
    zext_ln837_8 : IN STD_LOGIC_VECTOR (13 downto 0);
    buf2_circ_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf2_circ_V_ce0 : OUT STD_LOGIC;
    buf2_circ_V_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    buf2_circ_V_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf2_circ_V_1_ce0 : OUT STD_LOGIC;
    buf2_circ_V_1_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    buf2_circ_V_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf2_circ_V_2_ce0 : OUT STD_LOGIC;
    buf2_circ_V_2_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    buf2_circ_V_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf2_circ_V_3_ce0 : OUT STD_LOGIC;
    buf2_circ_V_3_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    buf2_circ_V_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf2_circ_V_4_ce0 : OUT STD_LOGIC;
    buf2_circ_V_4_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    buf2_circ_V_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf2_circ_V_5_ce0 : OUT STD_LOGIC;
    buf2_circ_V_5_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    buf2_circ_V_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf2_circ_V_6_ce0 : OUT STD_LOGIC;
    buf2_circ_V_6_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    buf2_circ_V_7_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf2_circ_V_7_ce0 : OUT STD_LOGIC;
    buf2_circ_V_7_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    buf2_circ_V_8_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf2_circ_V_8_ce0 : OUT STD_LOGIC;
    buf2_circ_V_8_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    buf2_circ_V_9_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    buf2_circ_V_9_ce0 : OUT STD_LOGIC;
    buf2_circ_V_9_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    add_ln233_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    phi_ln818_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    phi_ln818_1_out_ap_vld : OUT STD_LOGIC;
    phi_ln818_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    phi_ln818_2_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ecg_classifier_ecg_classifier_Pipeline_L3_IC_L3_K is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv10_280 : STD_LOGIC_VECTOR (9 downto 0) := "1010000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv8_5E : STD_LOGIC_VECTOR (7 downto 0) := "01011110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter29 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter30 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter31 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter32 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter33 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter34 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter35 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter36 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter37 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter21 : BOOLEAN;
    signal ap_block_state23_pp0_stage0_iter22 : BOOLEAN;
    signal ap_block_state24_pp0_stage0_iter23 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter24 : BOOLEAN;
    signal ap_block_state26_pp0_stage0_iter25 : BOOLEAN;
    signal ap_block_state27_pp0_stage0_iter26 : BOOLEAN;
    signal ap_block_state28_pp0_stage0_iter27 : BOOLEAN;
    signal ap_block_state29_pp0_stage0_iter28 : BOOLEAN;
    signal ap_block_state30_pp0_stage0_iter29 : BOOLEAN;
    signal ap_block_state31_pp0_stage0_iter30 : BOOLEAN;
    signal ap_block_state32_pp0_stage0_iter31 : BOOLEAN;
    signal ap_block_state33_pp0_stage0_iter32 : BOOLEAN;
    signal ap_block_state34_pp0_stage0_iter33 : BOOLEAN;
    signal ap_block_state35_pp0_stage0_iter34 : BOOLEAN;
    signal ap_block_state36_pp0_stage0_iter35 : BOOLEAN;
    signal ap_block_state37_pp0_stage0_iter36 : BOOLEAN;
    signal ap_block_state38_pp0_stage0_iter37 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln228_fu_413_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal clf_w_L3_W_V_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal clf_w_L3_W_V_ce0 : STD_LOGIC;
    signal clf_w_L3_W_V_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal clf_w_L3_W_V_address1 : STD_LOGIC_VECTOR (16 downto 0);
    signal clf_w_L3_W_V_ce1 : STD_LOGIC;
    signal clf_w_L3_W_V_q1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln837_8_cast_fu_371_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln837_8_cast_reg_990 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln228_reg_995 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter34_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_995_pp0_iter35_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_reg_999_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln228_fu_434_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter10_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter11_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter12_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter13_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter14_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter15_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter16_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter17_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter18_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter19_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter20_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter21_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter22_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter23_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter24_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter25_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter26_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter27_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter28_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter29_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter30_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter31_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter32_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln228_reg_1005_pp0_iter33_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln233_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter34_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_reg_1010_pp0_iter35_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln228_fu_596_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln228_reg_1020 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_710_p7 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_14_reg_1089 : STD_LOGIC_VECTOR (14 downto 0);
    signal clf_w_L3_W_V_load_reg_1094 : STD_LOGIC_VECTOR (1 downto 0);
    signal clf_w_L3_W_V_load_1_reg_1099 : STD_LOGIC_VECTOR (1 downto 0);
    signal r_V_6_fu_763_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal r_V_6_reg_1104 : STD_LOGIC_VECTOR (52 downto 0);
    signal r_V_7_fu_780_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal r_V_7_reg_1110 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln228_fu_617_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln837_11_fu_640_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln837_12_fu_651_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_ln818_2_fu_136 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal phi_ln818_1_fu_140 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_V_fu_144 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln225_cast_fu_363_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal lhs_V_5_fu_148 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln226_cast_fu_367_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal k_fu_152 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln230_fu_486_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_k_load : STD_LOGIC_VECTOR (2 downto 0);
    signal ic_1_fu_156 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln228_1_fu_511_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten65_fu_160 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln228_1_fu_419_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten65_load : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln233_fu_442_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln233_fu_446_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_458_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_cast23_cast_fu_466_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_smodpre5_fu_470_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_480_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_480_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln228_fu_505_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_522_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_531_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_2_fu_543_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln837_7_fu_553_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln837_6_fu_539_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln837_fu_518_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln837_3_fu_563_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_shl1_fu_572_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln837_9_fu_568_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_mid_fu_586_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_600_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln228_2_fu_610_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln837_fu_557_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln837_10_fu_631_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln837_5_fu_634_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln837_4_fu_580_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln837_6_fu_645_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_480_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_665_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_10_fu_674_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_11_fu_683_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_12_fu_692_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_13_fu_701_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_14_fu_710_p6 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_V_fu_726_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal select_ln233_fu_733_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal r_V_fu_740_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal shl_ln838_5_fu_748_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal r_V_6_fu_763_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln1270_fu_755_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal shl_ln2_fu_769_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal r_V_7_fu_780_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln230_fu_800_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln1347_2_fu_804_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln230_fu_812_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_V_6_fu_792_p3 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1347_fu_815_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln1347_fu_824_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal trunc_ln230_1_fu_848_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln1347_4_fu_852_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln230_1_fu_860_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_V_7_fu_840_p3 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1347_3_fu_863_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln1347_2_fu_872_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln230_1_fu_818_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln230_2_fu_866_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter27_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter28_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter29_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter30_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter31_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter32_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter33_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter34_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter35_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter36_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_classifier_urem_32s_4ns_3_36_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component ecg_classifier_mux_21_15_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component ecg_classifier_mux_53_15_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (14 downto 0);
        din3 : IN STD_LOGIC_VECTOR (14 downto 0);
        din4 : IN STD_LOGIC_VECTOR (14 downto 0);
        din5 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component ecg_classifier_mul_22s_31ns_53_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (30 downto 0);
        dout : OUT STD_LOGIC_VECTOR (52 downto 0) );
    end component;


    component ecg_classifier_ecg_classifier_Pipeline_L3_IC_L3_K_clf_w_L3_W_V_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        address1 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component ecg_classifier_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    clf_w_L3_W_V_U : component ecg_classifier_ecg_classifier_Pipeline_L3_IC_L3_K_clf_w_L3_W_V_ROM_AUTO_1R
    generic map (
        DataWidth => 2,
        AddressRange => 81920,
        AddressWidth => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => clf_w_L3_W_V_address0,
        ce0 => clf_w_L3_W_V_ce0,
        q0 => clf_w_L3_W_V_q0,
        address1 => clf_w_L3_W_V_address1,
        ce1 => clf_w_L3_W_V_ce1,
        q1 => clf_w_L3_W_V_q1);

    urem_32s_4ns_3_36_1_U91 : component ecg_classifier_urem_32s_4ns_3_36_1
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 4,
        dout_WIDTH => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_480_p0,
        din1 => grp_fu_480_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_480_p2);

    mux_21_15_1_1_U92 : component ecg_classifier_mux_21_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        din2_WIDTH => 1,
        dout_WIDTH => 15)
    port map (
        din0 => buf2_circ_V_q0,
        din1 => buf2_circ_V_1_q0,
        din2 => trunc_ln228_reg_1020,
        dout => tmp_9_fu_665_p4);

    mux_21_15_1_1_U93 : component ecg_classifier_mux_21_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        din2_WIDTH => 1,
        dout_WIDTH => 15)
    port map (
        din0 => buf2_circ_V_2_q0,
        din1 => buf2_circ_V_3_q0,
        din2 => trunc_ln228_reg_1020,
        dout => tmp_10_fu_674_p4);

    mux_21_15_1_1_U94 : component ecg_classifier_mux_21_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        din2_WIDTH => 1,
        dout_WIDTH => 15)
    port map (
        din0 => buf2_circ_V_4_q0,
        din1 => buf2_circ_V_5_q0,
        din2 => trunc_ln228_reg_1020,
        dout => tmp_11_fu_683_p4);

    mux_21_15_1_1_U95 : component ecg_classifier_mux_21_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        din2_WIDTH => 1,
        dout_WIDTH => 15)
    port map (
        din0 => buf2_circ_V_6_q0,
        din1 => buf2_circ_V_7_q0,
        din2 => trunc_ln228_reg_1020,
        dout => tmp_12_fu_692_p4);

    mux_21_15_1_1_U96 : component ecg_classifier_mux_21_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        din2_WIDTH => 1,
        dout_WIDTH => 15)
    port map (
        din0 => buf2_circ_V_8_q0,
        din1 => buf2_circ_V_9_q0,
        din2 => trunc_ln228_reg_1020,
        dout => tmp_13_fu_701_p4);

    mux_53_15_1_1_U97 : component ecg_classifier_mux_53_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        din2_WIDTH => 15,
        din3_WIDTH => 15,
        din4_WIDTH => 15,
        din5_WIDTH => 3,
        dout_WIDTH => 15)
    port map (
        din0 => tmp_9_fu_665_p4,
        din1 => tmp_10_fu_674_p4,
        din2 => tmp_11_fu_683_p4,
        din3 => tmp_12_fu_692_p4,
        din4 => tmp_13_fu_701_p4,
        din5 => tmp_14_fu_710_p6,
        dout => tmp_14_fu_710_p7);

    mul_22s_31ns_53_1_1_U98 : component ecg_classifier_mul_22s_31ns_53_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 22,
        din1_WIDTH => 31,
        dout_WIDTH => 53)
    port map (
        din0 => shl_ln838_5_fu_748_p3,
        din1 => r_V_6_fu_763_p1,
        dout => r_V_6_fu_763_p2);

    mul_22s_31ns_53_1_1_U99 : component ecg_classifier_mul_22s_31ns_53_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 22,
        din1_WIDTH => 31,
        dout_WIDTH => 53)
    port map (
        din0 => shl_ln2_fu_769_p3,
        din1 => r_V_7_fu_780_p1,
        dout => r_V_7_fu_780_p2);

    flow_control_loop_pipe_sequential_init_U : component ecg_classifier_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter36_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter29_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter30_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter30 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter31_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter31 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter32_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter32 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter33_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter33 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter34_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter34 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter35_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter35 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter36_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter36 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter37_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter37 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ic_1_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ic_1_fu_156 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter34 = ap_const_logic_1)) then 
                    ic_1_fu_156 <= select_ln228_1_fu_511_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten65_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln228_fu_413_p2 = ap_const_lv1_0))) then 
                    indvar_flatten65_fu_160 <= add_ln228_1_fu_419_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten65_fu_160 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    k_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln228_fu_413_p2 = ap_const_lv1_0))) then 
                    k_fu_152 <= add_ln230_fu_486_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_152 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_V_5_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    lhs_V_5_fu_148 <= sext_ln226_cast_fu_367_p1;
                elsif ((ap_enable_reg_pp0_iter37 = ap_const_logic_1)) then 
                    lhs_V_5_fu_148 <= add_ln1347_2_fu_872_p2(71 downto 24);
                end if;
            end if; 
        end if;
    end process;

    lhs_V_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    lhs_V_fu_144 <= sext_ln225_cast_fu_363_p1;
                elsif ((ap_enable_reg_pp0_iter37 = ap_const_logic_1)) then 
                    lhs_V_fu_144 <= add_ln1347_fu_824_p2(71 downto 24);
                end if;
            end if; 
        end if;
    end process;

    phi_ln818_1_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    phi_ln818_1_fu_140 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter37 = ap_const_logic_1)) then 
                    phi_ln818_1_fu_140 <= add_ln230_1_fu_818_p2(63 downto 32);
                end if;
            end if; 
        end if;
    end process;

    phi_ln818_2_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    phi_ln818_2_fu_136 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter37 = ap_const_logic_1)) then 
                    phi_ln818_2_fu_136 <= add_ln230_2_fu_866_p2(63 downto 32);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
                ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
                ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
                ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
                ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
                ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
                ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
                ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
                ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
                ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln228_reg_995_pp0_iter10_reg <= icmp_ln228_reg_995_pp0_iter9_reg;
                icmp_ln228_reg_995_pp0_iter11_reg <= icmp_ln228_reg_995_pp0_iter10_reg;
                icmp_ln228_reg_995_pp0_iter12_reg <= icmp_ln228_reg_995_pp0_iter11_reg;
                icmp_ln228_reg_995_pp0_iter13_reg <= icmp_ln228_reg_995_pp0_iter12_reg;
                icmp_ln228_reg_995_pp0_iter14_reg <= icmp_ln228_reg_995_pp0_iter13_reg;
                icmp_ln228_reg_995_pp0_iter15_reg <= icmp_ln228_reg_995_pp0_iter14_reg;
                icmp_ln228_reg_995_pp0_iter16_reg <= icmp_ln228_reg_995_pp0_iter15_reg;
                icmp_ln228_reg_995_pp0_iter17_reg <= icmp_ln228_reg_995_pp0_iter16_reg;
                icmp_ln228_reg_995_pp0_iter18_reg <= icmp_ln228_reg_995_pp0_iter17_reg;
                icmp_ln228_reg_995_pp0_iter19_reg <= icmp_ln228_reg_995_pp0_iter18_reg;
                icmp_ln228_reg_995_pp0_iter20_reg <= icmp_ln228_reg_995_pp0_iter19_reg;
                icmp_ln228_reg_995_pp0_iter21_reg <= icmp_ln228_reg_995_pp0_iter20_reg;
                icmp_ln228_reg_995_pp0_iter22_reg <= icmp_ln228_reg_995_pp0_iter21_reg;
                icmp_ln228_reg_995_pp0_iter23_reg <= icmp_ln228_reg_995_pp0_iter22_reg;
                icmp_ln228_reg_995_pp0_iter24_reg <= icmp_ln228_reg_995_pp0_iter23_reg;
                icmp_ln228_reg_995_pp0_iter25_reg <= icmp_ln228_reg_995_pp0_iter24_reg;
                icmp_ln228_reg_995_pp0_iter26_reg <= icmp_ln228_reg_995_pp0_iter25_reg;
                icmp_ln228_reg_995_pp0_iter27_reg <= icmp_ln228_reg_995_pp0_iter26_reg;
                icmp_ln228_reg_995_pp0_iter28_reg <= icmp_ln228_reg_995_pp0_iter27_reg;
                icmp_ln228_reg_995_pp0_iter29_reg <= icmp_ln228_reg_995_pp0_iter28_reg;
                icmp_ln228_reg_995_pp0_iter2_reg <= icmp_ln228_reg_995_pp0_iter1_reg;
                icmp_ln228_reg_995_pp0_iter30_reg <= icmp_ln228_reg_995_pp0_iter29_reg;
                icmp_ln228_reg_995_pp0_iter31_reg <= icmp_ln228_reg_995_pp0_iter30_reg;
                icmp_ln228_reg_995_pp0_iter32_reg <= icmp_ln228_reg_995_pp0_iter31_reg;
                icmp_ln228_reg_995_pp0_iter33_reg <= icmp_ln228_reg_995_pp0_iter32_reg;
                icmp_ln228_reg_995_pp0_iter34_reg <= icmp_ln228_reg_995_pp0_iter33_reg;
                icmp_ln228_reg_995_pp0_iter35_reg <= icmp_ln228_reg_995_pp0_iter34_reg;
                icmp_ln228_reg_995_pp0_iter3_reg <= icmp_ln228_reg_995_pp0_iter2_reg;
                icmp_ln228_reg_995_pp0_iter4_reg <= icmp_ln228_reg_995_pp0_iter3_reg;
                icmp_ln228_reg_995_pp0_iter5_reg <= icmp_ln228_reg_995_pp0_iter4_reg;
                icmp_ln228_reg_995_pp0_iter6_reg <= icmp_ln228_reg_995_pp0_iter5_reg;
                icmp_ln228_reg_995_pp0_iter7_reg <= icmp_ln228_reg_995_pp0_iter6_reg;
                icmp_ln228_reg_995_pp0_iter8_reg <= icmp_ln228_reg_995_pp0_iter7_reg;
                icmp_ln228_reg_995_pp0_iter9_reg <= icmp_ln228_reg_995_pp0_iter8_reg;
                icmp_ln230_reg_999_pp0_iter10_reg <= icmp_ln230_reg_999_pp0_iter9_reg;
                icmp_ln230_reg_999_pp0_iter11_reg <= icmp_ln230_reg_999_pp0_iter10_reg;
                icmp_ln230_reg_999_pp0_iter12_reg <= icmp_ln230_reg_999_pp0_iter11_reg;
                icmp_ln230_reg_999_pp0_iter13_reg <= icmp_ln230_reg_999_pp0_iter12_reg;
                icmp_ln230_reg_999_pp0_iter14_reg <= icmp_ln230_reg_999_pp0_iter13_reg;
                icmp_ln230_reg_999_pp0_iter15_reg <= icmp_ln230_reg_999_pp0_iter14_reg;
                icmp_ln230_reg_999_pp0_iter16_reg <= icmp_ln230_reg_999_pp0_iter15_reg;
                icmp_ln230_reg_999_pp0_iter17_reg <= icmp_ln230_reg_999_pp0_iter16_reg;
                icmp_ln230_reg_999_pp0_iter18_reg <= icmp_ln230_reg_999_pp0_iter17_reg;
                icmp_ln230_reg_999_pp0_iter19_reg <= icmp_ln230_reg_999_pp0_iter18_reg;
                icmp_ln230_reg_999_pp0_iter20_reg <= icmp_ln230_reg_999_pp0_iter19_reg;
                icmp_ln230_reg_999_pp0_iter21_reg <= icmp_ln230_reg_999_pp0_iter20_reg;
                icmp_ln230_reg_999_pp0_iter22_reg <= icmp_ln230_reg_999_pp0_iter21_reg;
                icmp_ln230_reg_999_pp0_iter23_reg <= icmp_ln230_reg_999_pp0_iter22_reg;
                icmp_ln230_reg_999_pp0_iter24_reg <= icmp_ln230_reg_999_pp0_iter23_reg;
                icmp_ln230_reg_999_pp0_iter25_reg <= icmp_ln230_reg_999_pp0_iter24_reg;
                icmp_ln230_reg_999_pp0_iter26_reg <= icmp_ln230_reg_999_pp0_iter25_reg;
                icmp_ln230_reg_999_pp0_iter27_reg <= icmp_ln230_reg_999_pp0_iter26_reg;
                icmp_ln230_reg_999_pp0_iter28_reg <= icmp_ln230_reg_999_pp0_iter27_reg;
                icmp_ln230_reg_999_pp0_iter29_reg <= icmp_ln230_reg_999_pp0_iter28_reg;
                icmp_ln230_reg_999_pp0_iter2_reg <= icmp_ln230_reg_999_pp0_iter1_reg;
                icmp_ln230_reg_999_pp0_iter30_reg <= icmp_ln230_reg_999_pp0_iter29_reg;
                icmp_ln230_reg_999_pp0_iter31_reg <= icmp_ln230_reg_999_pp0_iter30_reg;
                icmp_ln230_reg_999_pp0_iter32_reg <= icmp_ln230_reg_999_pp0_iter31_reg;
                icmp_ln230_reg_999_pp0_iter33_reg <= icmp_ln230_reg_999_pp0_iter32_reg;
                icmp_ln230_reg_999_pp0_iter3_reg <= icmp_ln230_reg_999_pp0_iter2_reg;
                icmp_ln230_reg_999_pp0_iter4_reg <= icmp_ln230_reg_999_pp0_iter3_reg;
                icmp_ln230_reg_999_pp0_iter5_reg <= icmp_ln230_reg_999_pp0_iter4_reg;
                icmp_ln230_reg_999_pp0_iter6_reg <= icmp_ln230_reg_999_pp0_iter5_reg;
                icmp_ln230_reg_999_pp0_iter7_reg <= icmp_ln230_reg_999_pp0_iter6_reg;
                icmp_ln230_reg_999_pp0_iter8_reg <= icmp_ln230_reg_999_pp0_iter7_reg;
                icmp_ln230_reg_999_pp0_iter9_reg <= icmp_ln230_reg_999_pp0_iter8_reg;
                icmp_ln233_reg_1010_pp0_iter10_reg <= icmp_ln233_reg_1010_pp0_iter9_reg;
                icmp_ln233_reg_1010_pp0_iter11_reg <= icmp_ln233_reg_1010_pp0_iter10_reg;
                icmp_ln233_reg_1010_pp0_iter12_reg <= icmp_ln233_reg_1010_pp0_iter11_reg;
                icmp_ln233_reg_1010_pp0_iter13_reg <= icmp_ln233_reg_1010_pp0_iter12_reg;
                icmp_ln233_reg_1010_pp0_iter14_reg <= icmp_ln233_reg_1010_pp0_iter13_reg;
                icmp_ln233_reg_1010_pp0_iter15_reg <= icmp_ln233_reg_1010_pp0_iter14_reg;
                icmp_ln233_reg_1010_pp0_iter16_reg <= icmp_ln233_reg_1010_pp0_iter15_reg;
                icmp_ln233_reg_1010_pp0_iter17_reg <= icmp_ln233_reg_1010_pp0_iter16_reg;
                icmp_ln233_reg_1010_pp0_iter18_reg <= icmp_ln233_reg_1010_pp0_iter17_reg;
                icmp_ln233_reg_1010_pp0_iter19_reg <= icmp_ln233_reg_1010_pp0_iter18_reg;
                icmp_ln233_reg_1010_pp0_iter20_reg <= icmp_ln233_reg_1010_pp0_iter19_reg;
                icmp_ln233_reg_1010_pp0_iter21_reg <= icmp_ln233_reg_1010_pp0_iter20_reg;
                icmp_ln233_reg_1010_pp0_iter22_reg <= icmp_ln233_reg_1010_pp0_iter21_reg;
                icmp_ln233_reg_1010_pp0_iter23_reg <= icmp_ln233_reg_1010_pp0_iter22_reg;
                icmp_ln233_reg_1010_pp0_iter24_reg <= icmp_ln233_reg_1010_pp0_iter23_reg;
                icmp_ln233_reg_1010_pp0_iter25_reg <= icmp_ln233_reg_1010_pp0_iter24_reg;
                icmp_ln233_reg_1010_pp0_iter26_reg <= icmp_ln233_reg_1010_pp0_iter25_reg;
                icmp_ln233_reg_1010_pp0_iter27_reg <= icmp_ln233_reg_1010_pp0_iter26_reg;
                icmp_ln233_reg_1010_pp0_iter28_reg <= icmp_ln233_reg_1010_pp0_iter27_reg;
                icmp_ln233_reg_1010_pp0_iter29_reg <= icmp_ln233_reg_1010_pp0_iter28_reg;
                icmp_ln233_reg_1010_pp0_iter2_reg <= icmp_ln233_reg_1010_pp0_iter1_reg;
                icmp_ln233_reg_1010_pp0_iter30_reg <= icmp_ln233_reg_1010_pp0_iter29_reg;
                icmp_ln233_reg_1010_pp0_iter31_reg <= icmp_ln233_reg_1010_pp0_iter30_reg;
                icmp_ln233_reg_1010_pp0_iter32_reg <= icmp_ln233_reg_1010_pp0_iter31_reg;
                icmp_ln233_reg_1010_pp0_iter33_reg <= icmp_ln233_reg_1010_pp0_iter32_reg;
                icmp_ln233_reg_1010_pp0_iter34_reg <= icmp_ln233_reg_1010_pp0_iter33_reg;
                icmp_ln233_reg_1010_pp0_iter35_reg <= icmp_ln233_reg_1010_pp0_iter34_reg;
                icmp_ln233_reg_1010_pp0_iter3_reg <= icmp_ln233_reg_1010_pp0_iter2_reg;
                icmp_ln233_reg_1010_pp0_iter4_reg <= icmp_ln233_reg_1010_pp0_iter3_reg;
                icmp_ln233_reg_1010_pp0_iter5_reg <= icmp_ln233_reg_1010_pp0_iter4_reg;
                icmp_ln233_reg_1010_pp0_iter6_reg <= icmp_ln233_reg_1010_pp0_iter5_reg;
                icmp_ln233_reg_1010_pp0_iter7_reg <= icmp_ln233_reg_1010_pp0_iter6_reg;
                icmp_ln233_reg_1010_pp0_iter8_reg <= icmp_ln233_reg_1010_pp0_iter7_reg;
                icmp_ln233_reg_1010_pp0_iter9_reg <= icmp_ln233_reg_1010_pp0_iter8_reg;
                r_V_6_reg_1104 <= r_V_6_fu_763_p2;
                r_V_7_reg_1110 <= r_V_7_fu_780_p2;
                select_ln228_reg_1005_pp0_iter10_reg <= select_ln228_reg_1005_pp0_iter9_reg;
                select_ln228_reg_1005_pp0_iter11_reg <= select_ln228_reg_1005_pp0_iter10_reg;
                select_ln228_reg_1005_pp0_iter12_reg <= select_ln228_reg_1005_pp0_iter11_reg;
                select_ln228_reg_1005_pp0_iter13_reg <= select_ln228_reg_1005_pp0_iter12_reg;
                select_ln228_reg_1005_pp0_iter14_reg <= select_ln228_reg_1005_pp0_iter13_reg;
                select_ln228_reg_1005_pp0_iter15_reg <= select_ln228_reg_1005_pp0_iter14_reg;
                select_ln228_reg_1005_pp0_iter16_reg <= select_ln228_reg_1005_pp0_iter15_reg;
                select_ln228_reg_1005_pp0_iter17_reg <= select_ln228_reg_1005_pp0_iter16_reg;
                select_ln228_reg_1005_pp0_iter18_reg <= select_ln228_reg_1005_pp0_iter17_reg;
                select_ln228_reg_1005_pp0_iter19_reg <= select_ln228_reg_1005_pp0_iter18_reg;
                select_ln228_reg_1005_pp0_iter20_reg <= select_ln228_reg_1005_pp0_iter19_reg;
                select_ln228_reg_1005_pp0_iter21_reg <= select_ln228_reg_1005_pp0_iter20_reg;
                select_ln228_reg_1005_pp0_iter22_reg <= select_ln228_reg_1005_pp0_iter21_reg;
                select_ln228_reg_1005_pp0_iter23_reg <= select_ln228_reg_1005_pp0_iter22_reg;
                select_ln228_reg_1005_pp0_iter24_reg <= select_ln228_reg_1005_pp0_iter23_reg;
                select_ln228_reg_1005_pp0_iter25_reg <= select_ln228_reg_1005_pp0_iter24_reg;
                select_ln228_reg_1005_pp0_iter26_reg <= select_ln228_reg_1005_pp0_iter25_reg;
                select_ln228_reg_1005_pp0_iter27_reg <= select_ln228_reg_1005_pp0_iter26_reg;
                select_ln228_reg_1005_pp0_iter28_reg <= select_ln228_reg_1005_pp0_iter27_reg;
                select_ln228_reg_1005_pp0_iter29_reg <= select_ln228_reg_1005_pp0_iter28_reg;
                select_ln228_reg_1005_pp0_iter2_reg <= select_ln228_reg_1005_pp0_iter1_reg;
                select_ln228_reg_1005_pp0_iter30_reg <= select_ln228_reg_1005_pp0_iter29_reg;
                select_ln228_reg_1005_pp0_iter31_reg <= select_ln228_reg_1005_pp0_iter30_reg;
                select_ln228_reg_1005_pp0_iter32_reg <= select_ln228_reg_1005_pp0_iter31_reg;
                select_ln228_reg_1005_pp0_iter33_reg <= select_ln228_reg_1005_pp0_iter32_reg;
                select_ln228_reg_1005_pp0_iter3_reg <= select_ln228_reg_1005_pp0_iter2_reg;
                select_ln228_reg_1005_pp0_iter4_reg <= select_ln228_reg_1005_pp0_iter3_reg;
                select_ln228_reg_1005_pp0_iter5_reg <= select_ln228_reg_1005_pp0_iter4_reg;
                select_ln228_reg_1005_pp0_iter6_reg <= select_ln228_reg_1005_pp0_iter5_reg;
                select_ln228_reg_1005_pp0_iter7_reg <= select_ln228_reg_1005_pp0_iter6_reg;
                select_ln228_reg_1005_pp0_iter8_reg <= select_ln228_reg_1005_pp0_iter7_reg;
                select_ln228_reg_1005_pp0_iter9_reg <= select_ln228_reg_1005_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln228_reg_995 <= icmp_ln228_fu_413_p2;
                icmp_ln228_reg_995_pp0_iter1_reg <= icmp_ln228_reg_995;
                icmp_ln230_reg_999_pp0_iter1_reg <= icmp_ln230_reg_999;
                icmp_ln233_reg_1010_pp0_iter1_reg <= icmp_ln233_reg_1010;
                select_ln228_reg_1005_pp0_iter1_reg <= select_ln228_reg_1005;
                    zext_ln837_8_cast_reg_990(13 downto 0) <= zext_ln837_8_cast_fu_371_p1(13 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter35 = ap_const_logic_1))) then
                clf_w_L3_W_V_load_1_reg_1099 <= clf_w_L3_W_V_q0;
                clf_w_L3_W_V_load_reg_1094 <= clf_w_L3_W_V_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln228_fu_413_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln230_reg_999 <= icmp_ln230_fu_428_p2;
                icmp_ln233_reg_1010 <= icmp_ln233_fu_452_p2;
                select_ln228_reg_1005 <= select_ln228_fu_434_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln233_reg_1010_pp0_iter34_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_14_reg_1089 <= tmp_14_fu_710_p7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln233_reg_1010_pp0_iter33_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                trunc_ln228_reg_1020 <= trunc_ln228_fu_596_p1;
            end if;
        end if;
    end process;
    zext_ln837_8_cast_reg_990(14) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1347_2_fu_872_p2 <= std_logic_vector(unsigned(lhs_V_7_fu_840_p3) + unsigned(sext_ln1347_3_fu_863_p1));
    add_ln1347_fu_824_p2 <= std_logic_vector(unsigned(lhs_V_6_fu_792_p3) + unsigned(sext_ln1347_fu_815_p1));
    add_ln228_1_fu_419_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten65_load) + unsigned(ap_const_lv10_1));
    add_ln228_fu_505_p2 <= std_logic_vector(unsigned(ic_1_fu_156) + unsigned(ap_const_lv8_1));
    add_ln230_1_fu_818_p2 <= std_logic_vector(unsigned(sext_ln1347_2_fu_804_p3) + unsigned(sext_ln230_fu_812_p1));
    add_ln230_2_fu_866_p2 <= std_logic_vector(unsigned(sext_ln1347_4_fu_852_p3) + unsigned(sext_ln230_1_fu_860_p1));
    add_ln230_fu_486_p2 <= std_logic_vector(unsigned(select_ln228_fu_434_p3) + unsigned(ap_const_lv3_1));
    add_ln233_fu_446_p2 <= std_logic_vector(unsigned(add_ln233_1) + unsigned(zext_ln233_fu_442_p1));
    add_ln837_3_fu_563_p2 <= std_logic_vector(unsigned(zext_ln837_8_cast_reg_990) + unsigned(zext_ln837_fu_518_p1));
    add_ln837_4_fu_580_p2 <= std_logic_vector(unsigned(p_shl1_fu_572_p3) + unsigned(zext_ln837_9_fu_568_p1));
    add_ln837_5_fu_634_p2 <= std_logic_vector(unsigned(add_ln837_fu_557_p2) + unsigned(zext_ln837_10_fu_631_p1));
    add_ln837_6_fu_645_p2 <= std_logic_vector(unsigned(add_ln837_4_fu_580_p2) + unsigned(zext_ln837_10_fu_631_p1));
    add_ln837_fu_557_p2 <= std_logic_vector(unsigned(zext_ln837_7_fu_553_p1) + unsigned(zext_ln837_6_fu_539_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage0_iter22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage0_iter23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage0_iter25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state27_pp0_stage0_iter26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state28_pp0_stage0_iter27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state29_pp0_stage0_iter28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state30_pp0_stage0_iter29 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state31_pp0_stage0_iter30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state32_pp0_stage0_iter31 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state33_pp0_stage0_iter32 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state34_pp0_stage0_iter33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state35_pp0_stage0_iter34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state36_pp0_stage0_iter35 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state37_pp0_stage0_iter36 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state38_pp0_stage0_iter37 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln228_fu_413_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln228_fu_413_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter36_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter36_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29, ap_enable_reg_pp0_iter30, ap_enable_reg_pp0_iter31, ap_enable_reg_pp0_iter32, ap_enable_reg_pp0_iter33, ap_enable_reg_pp0_iter34, ap_enable_reg_pp0_iter35, ap_enable_reg_pp0_iter36, ap_enable_reg_pp0_iter37)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter37 = ap_const_logic_0) and (ap_enable_reg_pp0_iter36 = ap_const_logic_0) and (ap_enable_reg_pp0_iter35 = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_0) and (ap_enable_reg_pp0_iter33 = ap_const_logic_0) and (ap_enable_reg_pp0_iter32 = ap_const_logic_0) and (ap_enable_reg_pp0_iter31 = ap_const_logic_0) and (ap_enable_reg_pp0_iter30 = ap_const_logic_0) and (ap_enable_reg_pp0_iter29 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten65_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten65_fu_160)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten65_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten65_load <= indvar_flatten65_fu_160;
        end if; 
    end process;


    ap_sig_allocacmp_k_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_152)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_k_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_k_load <= k_fu_152;
        end if; 
    end process;

    buf2_circ_V_1_address0 <= zext_ln228_fu_617_p1(6 - 1 downto 0);

    buf2_circ_V_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            buf2_circ_V_1_ce0 <= ap_const_logic_1;
        else 
            buf2_circ_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf2_circ_V_2_address0 <= zext_ln228_fu_617_p1(6 - 1 downto 0);

    buf2_circ_V_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            buf2_circ_V_2_ce0 <= ap_const_logic_1;
        else 
            buf2_circ_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf2_circ_V_3_address0 <= zext_ln228_fu_617_p1(6 - 1 downto 0);

    buf2_circ_V_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            buf2_circ_V_3_ce0 <= ap_const_logic_1;
        else 
            buf2_circ_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf2_circ_V_4_address0 <= zext_ln228_fu_617_p1(6 - 1 downto 0);

    buf2_circ_V_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            buf2_circ_V_4_ce0 <= ap_const_logic_1;
        else 
            buf2_circ_V_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf2_circ_V_5_address0 <= zext_ln228_fu_617_p1(6 - 1 downto 0);

    buf2_circ_V_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            buf2_circ_V_5_ce0 <= ap_const_logic_1;
        else 
            buf2_circ_V_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf2_circ_V_6_address0 <= zext_ln228_fu_617_p1(6 - 1 downto 0);

    buf2_circ_V_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            buf2_circ_V_6_ce0 <= ap_const_logic_1;
        else 
            buf2_circ_V_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf2_circ_V_7_address0 <= zext_ln228_fu_617_p1(6 - 1 downto 0);

    buf2_circ_V_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            buf2_circ_V_7_ce0 <= ap_const_logic_1;
        else 
            buf2_circ_V_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf2_circ_V_8_address0 <= zext_ln228_fu_617_p1(6 - 1 downto 0);

    buf2_circ_V_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            buf2_circ_V_8_ce0 <= ap_const_logic_1;
        else 
            buf2_circ_V_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf2_circ_V_9_address0 <= zext_ln228_fu_617_p1(6 - 1 downto 0);

    buf2_circ_V_9_ce0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            buf2_circ_V_9_ce0 <= ap_const_logic_1;
        else 
            buf2_circ_V_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf2_circ_V_address0 <= zext_ln228_fu_617_p1(6 - 1 downto 0);

    buf2_circ_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            buf2_circ_V_ce0 <= ap_const_logic_1;
        else 
            buf2_circ_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    clf_w_L3_W_V_address0 <= zext_ln837_12_fu_651_p1(17 - 1 downto 0);
    clf_w_L3_W_V_address1 <= zext_ln837_11_fu_640_p1(17 - 1 downto 0);

    clf_w_L3_W_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            clf_w_L3_W_V_ce0 <= ap_const_logic_1;
        else 
            clf_w_L3_W_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    clf_w_L3_W_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            clf_w_L3_W_V_ce1 <= ap_const_logic_1;
        else 
            clf_w_L3_W_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

        grp_fu_480_p0 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_smodpre5_fu_470_p2),32));

    grp_fu_480_p1 <= ap_const_lv32_5(4 - 1 downto 0);
    icmp_ln228_fu_413_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten65_load = ap_const_lv10_280) else "0";
    icmp_ln230_fu_428_p2 <= "1" when (ap_sig_allocacmp_k_load = ap_const_lv3_5) else "0";
    icmp_ln233_fu_452_p2 <= "1" when (unsigned(add_ln233_fu_446_p2) < unsigned(ap_const_lv8_5E)) else "0";
    lhs_V_6_fu_792_p3 <= (lhs_V_fu_144 & ap_const_lv24_0);
    lhs_V_7_fu_840_p3 <= (lhs_V_5_fu_148 & ap_const_lv24_0);
    p_cast23_cast_fu_466_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_458_p3),8));
    p_mid_fu_586_p4 <= add_ln228_fu_505_p2(6 downto 1);
    p_shl1_fu_572_p3 <= (add_ln837_3_fu_563_p2 & ap_const_lv2_0);
    p_smodpre5_fu_470_p2 <= (p_cast23_cast_fu_466_p1 xor add_ln233_fu_446_p2);
    phi_ln818_1_out <= phi_ln818_1_fu_140;

    phi_ln818_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln228_reg_995_pp0_iter35_reg)
    begin
        if (((icmp_ln228_reg_995_pp0_iter35_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            phi_ln818_1_out_ap_vld <= ap_const_logic_1;
        else 
            phi_ln818_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    phi_ln818_2_out <= phi_ln818_2_fu_136;

    phi_ln818_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln228_reg_995_pp0_iter35_reg)
    begin
        if (((icmp_ln228_reg_995_pp0_iter35_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            phi_ln818_2_out_ap_vld <= ap_const_logic_1;
        else 
            phi_ln818_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    r_V_6_fu_763_p1 <= zext_ln1270_fu_755_p1(31 - 1 downto 0);
    r_V_7_fu_780_p1 <= zext_ln1270_fu_755_p1(31 - 1 downto 0);
    r_V_fu_740_p3 <= (select_ln233_fu_733_p3 & ap_const_lv8_0);
    select_ln228_1_fu_511_p3 <= 
        add_ln228_fu_505_p2 when (icmp_ln230_reg_999_pp0_iter33_reg(0) = '1') else 
        ic_1_fu_156;
    select_ln228_2_fu_610_p3 <= 
        p_mid_fu_586_p4 when (icmp_ln230_reg_999_pp0_iter33_reg(0) = '1') else 
        tmp_s_fu_600_p4;
    select_ln228_fu_434_p3 <= 
        ap_const_lv3_0 when (icmp_ln230_fu_428_p2(0) = '1') else 
        ap_sig_allocacmp_k_load;
    select_ln233_fu_733_p3 <= 
        x_V_fu_726_p3 when (icmp_ln233_reg_1010_pp0_iter35_reg(0) = '1') else 
        ap_const_lv23_0;
    sext_ln1347_2_fu_804_p3 <= (trunc_ln230_fu_800_p1 & ap_const_lv24_0);
        sext_ln1347_3_fu_863_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_7_reg_1110),72));

    sext_ln1347_4_fu_852_p3 <= (trunc_ln230_1_fu_848_p1 & ap_const_lv24_0);
        sext_ln1347_fu_815_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_6_reg_1104),72));

        sext_ln225_cast_fu_363_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln225),48));

        sext_ln226_cast_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln226),48));

        sext_ln230_1_fu_860_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_7_reg_1110),64));

        sext_ln230_fu_812_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_6_reg_1104),64));

    shl_ln2_fu_769_p3 <= (clf_w_L3_W_V_load_1_reg_1099 & ap_const_lv20_0);
    shl_ln838_5_fu_748_p3 <= (clf_w_L3_W_V_load_reg_1094 & ap_const_lv20_0);
    tmp_14_fu_710_p6 <= grp_fu_480_p2(3 - 1 downto 0);
    tmp_1_fu_531_p3 <= (tmp_fu_522_p4 & select_ln228_1_fu_511_p3);
    tmp_2_fu_543_p4 <= ((tmp_fu_522_p4 & select_ln228_1_fu_511_p3) & ap_const_lv2_0);
    tmp_3_fu_458_p3 <= add_ln233_fu_446_p2(7 downto 7);
    tmp_fu_522_p4 <= oc_base(6 downto 1);
    tmp_s_fu_600_p4 <= ic_1_fu_156(6 downto 1);
    trunc_ln228_fu_596_p1 <= select_ln228_1_fu_511_p3(1 - 1 downto 0);
    trunc_ln230_1_fu_848_p1 <= lhs_V_5_fu_148(40 - 1 downto 0);
    trunc_ln230_fu_800_p1 <= lhs_V_fu_144(40 - 1 downto 0);
    x_V_fu_726_p3 <= (tmp_14_reg_1089 & ap_const_lv8_0);
    zext_ln1270_fu_755_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_fu_740_p3),53));
    zext_ln228_fu_617_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln228_2_fu_610_p3),64));
    zext_ln233_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln228_fu_434_p3),8));
    zext_ln837_10_fu_631_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln228_reg_1005_pp0_iter33_reg),17));
    zext_ln837_11_fu_640_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln837_5_fu_634_p2),64));
    zext_ln837_12_fu_651_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln837_6_fu_645_p2),64));
    zext_ln837_6_fu_539_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_531_p3),17));
    zext_ln837_7_fu_553_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_543_p4),17));
    zext_ln837_8_cast_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln837_8),15));
    zext_ln837_9_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln837_3_fu_563_p2),17));
    zext_ln837_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln228_1_fu_511_p3),15));
end behav;
