-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_classifier_ecg_classifier_Pipeline_ZNORM_APPLY is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    norm_buf_V_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    norm_buf_V_1_ce0 : OUT STD_LOGIC;
    norm_buf_V_1_we0 : OUT STD_LOGIC;
    norm_buf_V_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    norm_buf_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    norm_buf_V_ce0 : OUT STD_LOGIC;
    norm_buf_V_we0 : OUT STD_LOGIC;
    norm_buf_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    input_buf_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    input_buf_V_ce0 : OUT STD_LOGIC;
    input_buf_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_buf_V_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    input_buf_V_1_ce0 : OUT STD_LOGIC;
    input_buf_V_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    rhs : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln74 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of ecg_classifier_ecg_classifier_Pipeline_ZNORM_APPLY is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_BB : STD_LOGIC_VECTOR (7 downto 0) := "10111011";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln74_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sext_ln74_cast_fu_124_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln74_cast_reg_224 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal rhs_cast_fu_128_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal rhs_cast_reg_229 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln813_fu_170_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln813_reg_248 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln813_reg_248_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal norm_buf_V_addr_reg_253 : STD_LOGIC_VECTOR (6 downto 0);
    signal norm_buf_V_addr_reg_253_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal norm_buf_V_1_addr_reg_258 : STD_LOGIC_VECTOR (6 downto 0);
    signal norm_buf_V_1_addr_reg_258_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal ret_V_fu_192_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_reg_263 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln813_fu_162_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal t_fu_58 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_fu_146_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_t_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln813_1_fu_152_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal lhs_V_fu_179_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln813_fu_188_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal r_V_2_fu_200_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_2_fu_200_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_classifier_mux_21_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_classifier_mul_33s_32s_48_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (32 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component ecg_classifier_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_21_32_1_1_U22 : component ecg_classifier_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => input_buf_V_q0,
        din1 => input_buf_V_1_q0,
        din2 => trunc_ln813_reg_248,
        dout => lhs_V_fu_179_p4);

    mul_33s_32s_48_1_1_U23 : component ecg_classifier_mul_33s_32s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 33,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        din0 => ret_V_reg_263,
        din1 => r_V_2_fu_200_p1,
        dout => r_V_2_fu_200_p2);

    flow_control_loop_pipe_sequential_init_U : component ecg_classifier_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    t_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln74_fu_140_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    t_fu_58 <= add_ln74_fu_146_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_58 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                norm_buf_V_1_addr_reg_258_pp0_iter1_reg <= norm_buf_V_1_addr_reg_258;
                norm_buf_V_addr_reg_253_pp0_iter1_reg <= norm_buf_V_addr_reg_253;
                ret_V_reg_263 <= ret_V_fu_192_p2;
                rhs_cast_reg_229 <= rhs_cast_fu_128_p1;
                sext_ln74_cast_reg_224 <= sext_ln74_cast_fu_124_p1;
                trunc_ln813_reg_248_pp0_iter1_reg <= trunc_ln813_reg_248;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_fu_140_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                norm_buf_V_1_addr_reg_258 <= zext_ln813_fu_162_p1(7 - 1 downto 0);
                norm_buf_V_addr_reg_253 <= zext_ln813_fu_162_p1(7 - 1 downto 0);
                trunc_ln813_reg_248 <= trunc_ln813_fu_170_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln74_fu_146_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_t_2) + unsigned(ap_const_lv8_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln74_fu_140_p2)
    begin
        if (((icmp_ln74_fu_140_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_t_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, t_fu_58, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_t_2 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_t_2 <= t_fu_58;
        end if; 
    end process;

    icmp_ln74_fu_140_p2 <= "1" when (ap_sig_allocacmp_t_2 = ap_const_lv8_BB) else "0";
    input_buf_V_1_address0 <= zext_ln813_fu_162_p1(7 - 1 downto 0);

    input_buf_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_buf_V_1_ce0 <= ap_const_logic_1;
        else 
            input_buf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    input_buf_V_address0 <= zext_ln813_fu_162_p1(7 - 1 downto 0);

    input_buf_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_buf_V_ce0 <= ap_const_logic_1;
        else 
            input_buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln813_1_fu_152_p4 <= ap_sig_allocacmp_t_2(7 downto 1);
    norm_buf_V_1_address0 <= norm_buf_V_1_addr_reg_258_pp0_iter1_reg;

    norm_buf_V_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            norm_buf_V_1_ce0 <= ap_const_logic_1;
        else 
            norm_buf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    norm_buf_V_1_d0 <= r_V_2_fu_200_p2(47 downto 16);

    norm_buf_V_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln813_reg_248_pp0_iter1_reg)
    begin
        if (((trunc_ln813_reg_248_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            norm_buf_V_1_we0 <= ap_const_logic_1;
        else 
            norm_buf_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    norm_buf_V_address0 <= norm_buf_V_addr_reg_253_pp0_iter1_reg;

    norm_buf_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            norm_buf_V_ce0 <= ap_const_logic_1;
        else 
            norm_buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    norm_buf_V_d0 <= r_V_2_fu_200_p2(47 downto 16);

    norm_buf_V_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln813_reg_248_pp0_iter1_reg)
    begin
        if (((trunc_ln813_reg_248_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            norm_buf_V_we0 <= ap_const_logic_1;
        else 
            norm_buf_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    r_V_2_fu_200_p1 <= sext_ln74_cast_reg_224(32 - 1 downto 0);
    ret_V_fu_192_p2 <= std_logic_vector(signed(sext_ln813_fu_188_p1) - signed(rhs_cast_reg_229));
        rhs_cast_fu_128_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs),33));

        sext_ln74_cast_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln74),48));

        sext_ln813_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(lhs_V_fu_179_p4),33));

    trunc_ln813_fu_170_p1 <= ap_sig_allocacmp_t_2(1 - 1 downto 0);
    zext_ln813_fu_162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln813_1_fu_152_p4),64));
end behav;
