// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ecg_denoiser_conv_layer01234_fused_Pipeline_L2_IC_L2_K (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln143,
        sext_ln142,
        oc_base_1,
        zext_ln837_4,
        win12_V_1_address0,
        win12_V_1_ce0,
        win12_V_1_q0,
        win12_V_2_address0,
        win12_V_2_ce0,
        win12_V_2_q0,
        win12_V_3_address0,
        win12_V_3_ce0,
        win12_V_3_q0,
        phi_ln818_2_out,
        phi_ln818_2_out_ap_vld,
        phi_ln818_3_out,
        phi_ln818_3_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [24:0] sext_ln143;
input  [24:0] sext_ln142;
input  [5:0] oc_base_1;
input  [12:0] zext_ln837_4;
output  [6:0] win12_V_1_address0;
output   win12_V_1_ce0;
input  [30:0] win12_V_1_q0;
output  [6:0] win12_V_2_address0;
output   win12_V_2_ce0;
input  [30:0] win12_V_2_q0;
output  [6:0] win12_V_3_address0;
output   win12_V_3_ce0;
input  [30:0] win12_V_3_q0;
output  [31:0] phi_ln818_2_out;
output   phi_ln818_2_out_ap_vld;
output  [31:0] phi_ln818_3_out;
output   phi_ln818_3_out_ap_vld;

reg ap_idle;
reg win12_V_1_ce0;
reg win12_V_2_ce0;
reg win12_V_3_ce0;
reg phi_ln818_2_out_ap_vld;
reg phi_ln818_3_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln145_fu_290_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [15:0] denoiser_w_L2_W_V_address0;
reg    denoiser_w_L2_W_V_ce0;
wire   [14:0] denoiser_w_L2_W_V_q0;
wire   [15:0] denoiser_w_L2_W_V_address1;
reg    denoiser_w_L2_W_V_ce1;
wire   [14:0] denoiser_w_L2_W_V_q1;
wire    ap_block_pp0_stage0_11001;
wire   [13:0] zext_ln837_4_cast_fu_248_p1;
reg   [13:0] zext_ln837_4_cast_reg_738;
reg   [0:0] icmp_ln145_reg_743;
reg   [0:0] icmp_ln145_reg_743_pp0_iter1_reg;
wire   [2:0] select_ln145_fu_320_p3;
reg   [2:0] select_ln145_reg_747;
wire   [7:0] select_ln145_1_fu_328_p3;
reg   [7:0] select_ln145_1_reg_753;
wire   [31:0] x_V_fu_472_p7;
reg   [31:0] x_V_reg_785;
wire  signed [61:0] r_V_9_fu_510_p2;
reg  signed [61:0] r_V_9_reg_790;
wire  signed [61:0] r_V_10_fu_528_p2;
reg  signed [61:0] r_V_10_reg_796;
wire   [63:0] zext_ln145_fu_336_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln837_14_fu_450_p1;
wire   [63:0] zext_ln837_15_fu_467_p1;
reg   [31:0] phi_ln818_3_fu_110;
wire    ap_loop_init;
reg   [31:0] phi_ln818_2_fu_114;
reg   [47:0] lhs_fu_118;
wire  signed [47:0] sext_ln142_cast_fu_240_p1;
reg   [47:0] lhs_V_fu_122;
wire  signed [47:0] sext_ln143_cast_fu_244_p1;
reg   [2:0] k_fu_126;
wire   [2:0] add_ln147_fu_343_p2;
reg   [2:0] ap_sig_allocacmp_k_load;
reg   [7:0] ic_1_fu_130;
reg   [7:0] ap_sig_allocacmp_ic_1_load;
reg   [9:0] indvar_flatten25_fu_134;
wire   [9:0] add_ln145_1_fu_296_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten25_load;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln147_fu_314_p2;
wire   [7:0] add_ln145_fu_308_p2;
wire   [4:0] tmp_fu_367_p4;
wire   [5:0] zext_ln837_9_fu_376_p1;
wire   [14:0] tmp_s_fu_380_p4;
wire   [14:0] tmp_13_fu_393_p4;
wire   [15:0] zext_ln837_11_fu_402_p1;
wire   [15:0] zext_ln837_10_fu_389_p1;
wire   [13:0] zext_ln837_fu_364_p1;
wire   [13:0] add_ln837_3_fu_412_p2;
wire   [15:0] add_ln837_fu_406_p2;
wire   [15:0] zext_ln837_13_fu_441_p1;
wire   [15:0] add_ln837_4_fu_444_p2;
wire   [15:0] p_shl3_fu_421_p3;
wire   [15:0] zext_ln837_12_fu_417_p1;
wire   [15:0] add_ln837_5_fu_455_p2;
wire   [15:0] add_ln837_6_fu_461_p2;
wire   [31:0] x_V_fu_472_p3;
wire   [31:0] x_V_fu_472_p4;
wire   [31:0] x_V_fu_472_p5;
wire   [39:0] r_V_fu_487_p3;
wire  signed [22:0] shl_ln838_s_fu_494_p3;
wire  signed [39:0] r_V_9_fu_510_p1;
wire  signed [61:0] sext_ln1270_fu_502_p1;
wire  signed [22:0] shl_ln838_2_fu_516_p3;
wire  signed [39:0] r_V_10_fu_528_p1;
wire   [39:0] trunc_ln147_fu_548_p1;
wire   [63:0] sext_ln1347_5_fu_552_p3;
wire  signed [63:0] sext_ln147_fu_560_p1;
wire   [71:0] lhs_3_fu_540_p3;
wire  signed [71:0] sext_ln1347_fu_563_p1;
wire   [71:0] add_ln1347_fu_572_p2;
wire   [39:0] trunc_ln147_1_fu_596_p1;
wire   [63:0] sext_ln1347_7_fu_600_p3;
wire  signed [63:0] sext_ln147_1_fu_608_p1;
wire   [71:0] lhs_V_3_fu_588_p3;
wire  signed [71:0] sext_ln1347_2_fu_611_p1;
wire   [71:0] add_ln1347_2_fu_620_p2;
wire   [63:0] add_ln147_1_fu_566_p2;
wire   [63:0] add_ln147_2_fu_614_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

ecg_denoiser_conv_layer01234_fused_Pipeline_L2_IC_L2_K_denoiser_w_L2_W_V_ROM_NP_LUTRAM_1R #(
    .DataWidth( 15 ),
    .AddressRange( 40960 ),
    .AddressWidth( 16 ))
denoiser_w_L2_W_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(denoiser_w_L2_W_V_address0),
    .ce0(denoiser_w_L2_W_V_ce0),
    .q0(denoiser_w_L2_W_V_q0),
    .address1(denoiser_w_L2_W_V_address1),
    .ce1(denoiser_w_L2_W_V_ce1),
    .q1(denoiser_w_L2_W_V_q1)
);

ecg_denoiser_mux_53_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_53_32_1_1_U60(
    .din0(32'd0),
    .din1(32'd0),
    .din2(x_V_fu_472_p3),
    .din3(x_V_fu_472_p4),
    .din4(x_V_fu_472_p5),
    .din5(select_ln145_reg_747),
    .dout(x_V_fu_472_p7)
);

ecg_denoiser_mul_23s_40s_62_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 40 ),
    .dout_WIDTH( 62 ))
mul_23s_40s_62_1_1_U61(
    .din0(shl_ln838_s_fu_494_p3),
    .din1(r_V_9_fu_510_p1),
    .dout(r_V_9_fu_510_p2)
);

ecg_denoiser_mul_23s_40s_62_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 40 ),
    .dout_WIDTH( 62 ))
mul_23s_40s_62_1_1_U62(
    .din0(shl_ln838_2_fu_516_p3),
    .din1(r_V_10_fu_528_p1),
    .dout(r_V_10_fu_528_p2)
);

ecg_denoiser_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln145_fu_290_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ic_1_fu_130 <= select_ln145_1_fu_328_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ic_1_fu_130 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln145_fu_290_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten25_fu_134 <= add_ln145_1_fu_296_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten25_fu_134 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln145_fu_290_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_126 <= add_ln147_fu_343_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_126 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            lhs_V_fu_122 <= sext_ln143_cast_fu_244_p1;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            lhs_V_fu_122 <= {{add_ln1347_2_fu_620_p2[71:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            lhs_fu_118 <= sext_ln142_cast_fu_240_p1;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            lhs_fu_118 <= {{add_ln1347_fu_572_p2[71:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            phi_ln818_2_fu_114 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            phi_ln818_2_fu_114 <= {{add_ln147_1_fu_566_p2[63:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            phi_ln818_3_fu_110 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            phi_ln818_3_fu_110 <= {{add_ln147_2_fu_614_p2[63:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln145_reg_743 <= icmp_ln145_fu_290_p2;
        icmp_ln145_reg_743_pp0_iter1_reg <= icmp_ln145_reg_743;
        x_V_reg_785 <= x_V_fu_472_p7;
        zext_ln837_4_cast_reg_738[12 : 0] <= zext_ln837_4_cast_fu_248_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        r_V_10_reg_796 <= r_V_10_fu_528_p2;
        r_V_9_reg_790 <= r_V_9_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln145_fu_290_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln145_1_reg_753 <= select_ln145_1_fu_328_p3;
        select_ln145_reg_747 <= select_ln145_fu_320_p3;
    end
end

always @ (*) begin
    if (((icmp_ln145_fu_290_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ic_1_load = 8'd0;
    end else begin
        ap_sig_allocacmp_ic_1_load = ic_1_fu_130;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten25_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten25_load = indvar_flatten25_fu_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_load = 3'd0;
    end else begin
        ap_sig_allocacmp_k_load = k_fu_126;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        denoiser_w_L2_W_V_ce0 = 1'b1;
    end else begin
        denoiser_w_L2_W_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        denoiser_w_L2_W_V_ce1 = 1'b1;
    end else begin
        denoiser_w_L2_W_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln145_reg_743_pp0_iter1_reg == 1'd1))) begin
        phi_ln818_2_out_ap_vld = 1'b1;
    end else begin
        phi_ln818_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln145_reg_743_pp0_iter1_reg == 1'd1))) begin
        phi_ln818_3_out_ap_vld = 1'b1;
    end else begin
        phi_ln818_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        win12_V_1_ce0 = 1'b1;
    end else begin
        win12_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        win12_V_2_ce0 = 1'b1;
    end else begin
        win12_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        win12_V_3_ce0 = 1'b1;
    end else begin
        win12_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1347_2_fu_620_p2 = ($signed(lhs_V_3_fu_588_p3) + $signed(sext_ln1347_2_fu_611_p1));

assign add_ln1347_fu_572_p2 = ($signed(lhs_3_fu_540_p3) + $signed(sext_ln1347_fu_563_p1));

assign add_ln145_1_fu_296_p2 = (ap_sig_allocacmp_indvar_flatten25_load + 10'd1);

assign add_ln145_fu_308_p2 = (ap_sig_allocacmp_ic_1_load + 8'd1);

assign add_ln147_1_fu_566_p2 = ($signed(sext_ln1347_5_fu_552_p3) + $signed(sext_ln147_fu_560_p1));

assign add_ln147_2_fu_614_p2 = ($signed(sext_ln1347_7_fu_600_p3) + $signed(sext_ln147_1_fu_608_p1));

assign add_ln147_fu_343_p2 = (select_ln145_fu_320_p3 + 3'd1);

assign add_ln837_3_fu_412_p2 = (zext_ln837_4_cast_reg_738 + zext_ln837_fu_364_p1);

assign add_ln837_4_fu_444_p2 = (add_ln837_fu_406_p2 + zext_ln837_13_fu_441_p1);

assign add_ln837_5_fu_455_p2 = (p_shl3_fu_421_p3 + zext_ln837_12_fu_417_p1);

assign add_ln837_6_fu_461_p2 = (add_ln837_5_fu_455_p2 + zext_ln837_13_fu_441_p1);

assign add_ln837_fu_406_p2 = (zext_ln837_11_fu_402_p1 + zext_ln837_10_fu_389_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign denoiser_w_L2_W_V_address0 = zext_ln837_15_fu_467_p1;

assign denoiser_w_L2_W_V_address1 = zext_ln837_14_fu_450_p1;

assign icmp_ln145_fu_290_p2 = ((ap_sig_allocacmp_indvar_flatten25_load == 10'd640) ? 1'b1 : 1'b0);

assign icmp_ln147_fu_314_p2 = ((ap_sig_allocacmp_k_load == 3'd5) ? 1'b1 : 1'b0);

assign lhs_3_fu_540_p3 = {{lhs_fu_118}, {24'd0}};

assign lhs_V_3_fu_588_p3 = {{lhs_V_fu_122}, {24'd0}};

assign p_shl3_fu_421_p3 = {{add_ln837_3_fu_412_p2}, {2'd0}};

assign phi_ln818_2_out = phi_ln818_2_fu_114;

assign phi_ln818_3_out = phi_ln818_3_fu_110;

assign r_V_10_fu_528_p1 = sext_ln1270_fu_502_p1;

assign r_V_9_fu_510_p1 = sext_ln1270_fu_502_p1;

assign r_V_fu_487_p3 = {{x_V_reg_785}, {8'd0}};

assign select_ln145_1_fu_328_p3 = ((icmp_ln147_fu_314_p2[0:0] == 1'b1) ? add_ln145_fu_308_p2 : ap_sig_allocacmp_ic_1_load);

assign select_ln145_fu_320_p3 = ((icmp_ln147_fu_314_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_k_load);

assign sext_ln1270_fu_502_p1 = $signed(r_V_fu_487_p3);

assign sext_ln1347_2_fu_611_p1 = r_V_10_reg_796;

assign sext_ln1347_5_fu_552_p3 = {{trunc_ln147_fu_548_p1}, {24'd0}};

assign sext_ln1347_7_fu_600_p3 = {{trunc_ln147_1_fu_596_p1}, {24'd0}};

assign sext_ln1347_fu_563_p1 = r_V_9_reg_790;

assign sext_ln142_cast_fu_240_p1 = $signed(sext_ln142);

assign sext_ln143_cast_fu_244_p1 = $signed(sext_ln143);

assign sext_ln147_1_fu_608_p1 = r_V_10_reg_796;

assign sext_ln147_fu_560_p1 = r_V_9_reg_790;

assign shl_ln838_2_fu_516_p3 = {{denoiser_w_L2_W_V_q0}, {8'd0}};

assign shl_ln838_s_fu_494_p3 = {{denoiser_w_L2_W_V_q1}, {8'd0}};

assign tmp_13_fu_393_p4 = {{{tmp_fu_367_p4}, {select_ln145_1_reg_753}}, {2'd0}};

assign tmp_fu_367_p4 = {{oc_base_1[5:1]}};

assign tmp_s_fu_380_p4 = {{{{1'd0}, {zext_ln837_9_fu_376_p1}}}, {select_ln145_1_reg_753}};

assign trunc_ln147_1_fu_596_p1 = lhs_V_fu_122[39:0];

assign trunc_ln147_fu_548_p1 = lhs_fu_118[39:0];

assign win12_V_1_address0 = zext_ln145_fu_336_p1;

assign win12_V_2_address0 = zext_ln145_fu_336_p1;

assign win12_V_3_address0 = zext_ln145_fu_336_p1;

assign x_V_fu_472_p3 = win12_V_1_q0;

assign x_V_fu_472_p4 = win12_V_2_q0;

assign x_V_fu_472_p5 = win12_V_3_q0;

assign zext_ln145_fu_336_p1 = select_ln145_1_fu_328_p3;

assign zext_ln837_10_fu_389_p1 = tmp_s_fu_380_p4;

assign zext_ln837_11_fu_402_p1 = tmp_13_fu_393_p4;

assign zext_ln837_12_fu_417_p1 = add_ln837_3_fu_412_p2;

assign zext_ln837_13_fu_441_p1 = select_ln145_reg_747;

assign zext_ln837_14_fu_450_p1 = add_ln837_4_fu_444_p2;

assign zext_ln837_15_fu_467_p1 = add_ln837_6_fu_461_p2;

assign zext_ln837_4_cast_fu_248_p1 = zext_ln837_4;

assign zext_ln837_9_fu_376_p1 = tmp_fu_367_p4;

assign zext_ln837_fu_364_p1 = select_ln145_1_reg_753;

always @ (posedge ap_clk) begin
    zext_ln837_4_cast_reg_738[13] <= 1'b0;
end

endmodule //ecg_denoiser_conv_layer01234_fused_Pipeline_L2_IC_L2_K
