// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ecg_denoiser_ecg_denoiser,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z030-sbg485-2,HLS_INPUT_CLOCK=13.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.154250,HLS_SYN_LAT=19755865,HLS_SYN_TPT=none,HLS_SYN_MEM=84,HLS_SYN_DSP=0,HLS_SYN_FF=11618,HLS_SYN_LUT=33068,HLS_VERSION=2022_2}" *)

module ecg_denoiser (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST
);

parameter    ap_ST_fsm_state1 = 69'd1;
parameter    ap_ST_fsm_state2 = 69'd2;
parameter    ap_ST_fsm_state3 = 69'd4;
parameter    ap_ST_fsm_state4 = 69'd8;
parameter    ap_ST_fsm_state5 = 69'd16;
parameter    ap_ST_fsm_state6 = 69'd32;
parameter    ap_ST_fsm_state7 = 69'd64;
parameter    ap_ST_fsm_state8 = 69'd128;
parameter    ap_ST_fsm_state9 = 69'd256;
parameter    ap_ST_fsm_state10 = 69'd512;
parameter    ap_ST_fsm_state11 = 69'd1024;
parameter    ap_ST_fsm_state12 = 69'd2048;
parameter    ap_ST_fsm_state13 = 69'd4096;
parameter    ap_ST_fsm_state14 = 69'd8192;
parameter    ap_ST_fsm_state15 = 69'd16384;
parameter    ap_ST_fsm_state16 = 69'd32768;
parameter    ap_ST_fsm_state17 = 69'd65536;
parameter    ap_ST_fsm_state18 = 69'd131072;
parameter    ap_ST_fsm_state19 = 69'd262144;
parameter    ap_ST_fsm_state20 = 69'd524288;
parameter    ap_ST_fsm_state21 = 69'd1048576;
parameter    ap_ST_fsm_state22 = 69'd2097152;
parameter    ap_ST_fsm_state23 = 69'd4194304;
parameter    ap_ST_fsm_state24 = 69'd8388608;
parameter    ap_ST_fsm_state25 = 69'd16777216;
parameter    ap_ST_fsm_state26 = 69'd33554432;
parameter    ap_ST_fsm_state27 = 69'd67108864;
parameter    ap_ST_fsm_state28 = 69'd134217728;
parameter    ap_ST_fsm_state29 = 69'd268435456;
parameter    ap_ST_fsm_state30 = 69'd536870912;
parameter    ap_ST_fsm_state31 = 69'd1073741824;
parameter    ap_ST_fsm_state32 = 69'd2147483648;
parameter    ap_ST_fsm_state33 = 69'd4294967296;
parameter    ap_ST_fsm_state34 = 69'd8589934592;
parameter    ap_ST_fsm_state35 = 69'd17179869184;
parameter    ap_ST_fsm_state36 = 69'd34359738368;
parameter    ap_ST_fsm_state37 = 69'd68719476736;
parameter    ap_ST_fsm_state38 = 69'd137438953472;
parameter    ap_ST_fsm_state39 = 69'd274877906944;
parameter    ap_ST_fsm_state40 = 69'd549755813888;
parameter    ap_ST_fsm_state41 = 69'd1099511627776;
parameter    ap_ST_fsm_state42 = 69'd2199023255552;
parameter    ap_ST_fsm_state43 = 69'd4398046511104;
parameter    ap_ST_fsm_state44 = 69'd8796093022208;
parameter    ap_ST_fsm_state45 = 69'd17592186044416;
parameter    ap_ST_fsm_state46 = 69'd35184372088832;
parameter    ap_ST_fsm_state47 = 69'd70368744177664;
parameter    ap_ST_fsm_state48 = 69'd140737488355328;
parameter    ap_ST_fsm_state49 = 69'd281474976710656;
parameter    ap_ST_fsm_state50 = 69'd562949953421312;
parameter    ap_ST_fsm_state51 = 69'd1125899906842624;
parameter    ap_ST_fsm_state52 = 69'd2251799813685248;
parameter    ap_ST_fsm_state53 = 69'd4503599627370496;
parameter    ap_ST_fsm_state54 = 69'd9007199254740992;
parameter    ap_ST_fsm_state55 = 69'd18014398509481984;
parameter    ap_ST_fsm_state56 = 69'd36028797018963968;
parameter    ap_ST_fsm_state57 = 69'd72057594037927936;
parameter    ap_ST_fsm_state58 = 69'd144115188075855872;
parameter    ap_ST_fsm_state59 = 69'd288230376151711744;
parameter    ap_ST_fsm_state60 = 69'd576460752303423488;
parameter    ap_ST_fsm_state61 = 69'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 69'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 69'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 69'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 69'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 69'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 69'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 69'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 69'd295147905179352825856;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [68:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] mean_fx_V_reg_972;
wire    ap_CS_fsm_state6;
reg   [31:0] var_fx_reg_978;
wire    ap_CS_fsm_state8;
reg   [0:0] p_Result_6_reg_985;
wire   [0:0] icmp_ln1090_fu_385_p2;
reg   [0:0] icmp_ln1090_reg_991;
wire    ap_CS_fsm_state9;
wire   [31:0] tmp_V_2_fu_395_p3;
reg   [31:0] tmp_V_2_reg_996;
wire   [31:0] sub_ln1099_fu_419_p2;
reg   [31:0] sub_ln1099_reg_1001;
wire   [1:0] or_ln_fu_519_p3;
reg   [1:0] or_ln_reg_1007;
wire   [0:0] icmp_ln1113_fu_527_p2;
reg   [0:0] icmp_ln1113_reg_1012;
wire   [7:0] trunc_ln1098_fu_533_p1;
reg   [7:0] trunc_ln1098_reg_1017;
wire   [31:0] var_fx_f_fu_654_p3;
reg   [31:0] var_fx_f_reg_1022;
wire    ap_CS_fsm_state10;
wire   [31:0] var_safe_fu_702_p3;
reg   [31:0] var_safe_reg_1029;
wire    ap_CS_fsm_state12;
wire   [31:0] grp_fu_325_p2;
reg   [31:0] d_assign_reg_1034;
wire    ap_CS_fsm_state22;
wire   [53:0] man_V_2_fu_761_p3;
reg   [53:0] man_V_2_reg_1040;
wire    ap_CS_fsm_state24;
wire   [0:0] icmp_ln560_fu_769_p2;
reg   [0:0] icmp_ln560_reg_1045;
wire   [0:0] icmp_ln570_fu_781_p2;
reg   [0:0] icmp_ln570_reg_1052;
wire  signed [11:0] sh_amt_fu_799_p3;
reg  signed [11:0] sh_amt_reg_1057;
wire   [0:0] icmp_ln571_fu_807_p2;
reg   [0:0] icmp_ln571_reg_1063;
wire   [31:0] trunc_ln572_fu_813_p1;
reg   [31:0] trunc_ln572_reg_1069;
wire   [0:0] icmp_ln592_fu_827_p2;
reg   [0:0] icmp_ln592_reg_1075;
wire   [31:0] std_fx_V_fu_939_p3;
reg  signed [31:0] std_fx_V_reg_1080;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
wire   [31:0] inv_std_fx_V_fu_955_p1;
reg   [31:0] inv_std_fx_V_reg_1090;
wire    ap_CS_fsm_state63;
reg   [7:0] input_buf_V_address0;
reg    input_buf_V_ce0;
reg    input_buf_V_we0;
wire   [31:0] input_buf_V_q0;
reg   [7:0] input_buf_V_1_address0;
reg    input_buf_V_1_ce0;
reg    input_buf_V_1_we0;
wire   [31:0] input_buf_V_1_q0;
reg   [7:0] norm_buf_V_address0;
reg    norm_buf_V_ce0;
reg    norm_buf_V_we0;
wire   [31:0] norm_buf_V_q0;
reg   [7:0] norm_buf_V_1_address0;
reg    norm_buf_V_1_ce0;
reg    norm_buf_V_1_we0;
wire   [31:0] norm_buf_V_1_q0;
reg   [8:0] buf41210_address0;
reg    buf41210_ce0;
reg    buf41210_we0;
wire   [31:0] buf41210_q0;
wire    grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_start;
wire    grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_done;
wire    grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_idle;
wire    grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_ready;
wire   [7:0] grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_1_address0;
wire    grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_1_ce0;
wire    grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_1_we0;
wire   [31:0] grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_1_d0;
wire   [7:0] grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_address0;
wire    grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_ce0;
wire    grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_we0;
wire   [31:0] grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_d0;
wire    grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_in_stream_TREADY;
wire    grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_start;
wire    grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_done;
wire    grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_idle;
wire    grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_ready;
wire   [7:0] grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_input_buf_V_address0;
wire    grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_input_buf_V_ce0;
wire   [7:0] grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_input_buf_V_1_address0;
wire    grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_input_buf_V_1_ce0;
wire  signed [47:0] grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_mean_acc_V_out;
wire    grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_mean_acc_V_out_ap_vld;
wire    grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_start;
wire    grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_done;
wire    grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_idle;
wire    grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_ready;
wire   [7:0] grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_input_buf_V_address0;
wire    grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_input_buf_V_ce0;
wire   [7:0] grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_input_buf_V_1_address0;
wire    grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_input_buf_V_1_ce0;
wire  signed [47:0] grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_var_acc_V_2_out;
wire    grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_var_acc_V_2_out_ap_vld;
wire    grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_start;
wire    grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_done;
wire    grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_idle;
wire    grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_ready;
wire   [7:0] grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_1_address0;
wire    grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_1_ce0;
wire    grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_1_we0;
wire   [31:0] grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_1_d0;
wire   [7:0] grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_address0;
wire    grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_ce0;
wire    grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_we0;
wire   [31:0] grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_d0;
wire   [7:0] grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_input_buf_V_address0;
wire    grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_input_buf_V_ce0;
wire   [7:0] grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_input_buf_V_1_address0;
wire    grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_input_buf_V_1_ce0;
wire    grp_conv_layer01234_fused_fu_273_ap_start;
wire    grp_conv_layer01234_fused_fu_273_ap_done;
wire    grp_conv_layer01234_fused_fu_273_ap_idle;
wire    grp_conv_layer01234_fused_fu_273_ap_ready;
wire   [7:0] grp_conv_layer01234_fused_fu_273_in_0_address0;
wire    grp_conv_layer01234_fused_fu_273_in_0_ce0;
wire   [7:0] grp_conv_layer01234_fused_fu_273_in_1_address0;
wire    grp_conv_layer01234_fused_fu_273_in_1_ce0;
wire   [8:0] grp_conv_layer01234_fused_fu_273_out_r_address0;
wire    grp_conv_layer01234_fused_fu_273_out_r_ce0;
wire    grp_conv_layer01234_fused_fu_273_out_r_we0;
wire   [31:0] grp_conv_layer01234_fused_fu_273_out_r_d0;
wire    grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_start;
wire    grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_done;
wire    grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_idle;
wire    grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_ready;
wire    grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TREADY;
wire   [8:0] grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_buf41210_address0;
wire    grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_buf41210_ce0;
wire   [31:0] grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TDATA;
wire    grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TVALID;
wire   [3:0] grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TKEEP;
wire   [3:0] grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TSTRB;
wire   [0:0] grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TUSER;
wire   [0:0] grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TLAST;
wire   [0:0] grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TID;
wire   [0:0] grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TDEST;
reg    grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_start_reg;
wire    ap_CS_fsm_state64;
reg    grp_conv_layer01234_fused_fu_273_ap_start_reg;
wire    ap_CS_fsm_state65;
wire    ap_CS_fsm_state66;
reg    grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_start_reg;
wire    ap_CS_fsm_state67;
wire    ap_CS_fsm_state68;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state13;
wire   [8:0] r_V_fu_337_p1;
wire   [55:0] r_V_fu_337_p2;
wire   [8:0] r_V_3_fu_361_p1;
wire   [55:0] r_V_3_fu_361_p2;
wire   [31:0] tmp_V_fu_390_p2;
reg   [31:0] p_Result_7_fu_401_p4;
reg   [31:0] l_fu_411_p3;
wire   [31:0] lsb_index_fu_425_p2;
wire   [30:0] tmp_fu_431_p4;
wire   [4:0] trunc_ln1102_fu_447_p1;
wire   [4:0] sub_ln1102_fu_451_p2;
wire   [31:0] zext_ln1102_fu_457_p1;
wire   [31:0] lshr_ln1102_fu_461_p2;
wire   [31:0] p_Result_s_fu_467_p2;
wire   [0:0] icmp_ln1101_fu_441_p2;
wire   [0:0] icmp_ln1102_fu_473_p2;
wire   [0:0] tmp_1_fu_485_p3;
wire   [0:0] p_Result_1_fu_499_p3;
wire   [0:0] xor_ln1104_fu_493_p2;
wire   [0:0] and_ln1104_fu_507_p2;
wire   [0:0] a_fu_479_p2;
wire   [0:0] or_ln1104_fu_513_p2;
wire   [31:0] add_ln1113_fu_540_p2;
wire   [63:0] zext_ln1112_fu_537_p1;
wire   [63:0] zext_ln1113_fu_545_p1;
wire   [31:0] sub_ln1114_fu_555_p2;
wire   [63:0] zext_ln1114_fu_560_p1;
wire   [63:0] lshr_ln1113_fu_549_p2;
wire   [63:0] shl_ln1114_fu_564_p2;
wire   [63:0] m_2_fu_570_p3;
wire   [63:0] zext_ln1116_fu_577_p1;
wire   [63:0] m_3_fu_580_p2;
wire   [62:0] m_4_fu_586_p4;
wire   [0:0] p_Result_2_fu_600_p3;
wire   [7:0] sub_ln1119_fu_616_p2;
wire   [7:0] select_ln1098_fu_608_p3;
wire   [7:0] add_ln1124_fu_621_p2;
wire   [63:0] zext_ln1117_fu_596_p1;
wire   [8:0] tmp_5_fu_627_p3;
wire   [63:0] p_Result_8_fu_634_p5;
wire   [31:0] LD_fu_646_p1;
wire   [31:0] bitcast_ln766_fu_650_p1;
wire   [31:0] bitcast_ln267_fu_661_p1;
wire   [7:0] tmp_4_fu_664_p4;
wire   [22:0] trunc_ln267_fu_674_p1;
wire   [0:0] icmp_ln267_1_fu_684_p2;
wire   [0:0] icmp_ln267_fu_678_p2;
wire   [0:0] or_ln267_fu_690_p2;
wire   [0:0] grp_fu_320_p2;
wire   [0:0] and_ln267_fu_696_p2;
wire   [63:0] grp_fu_317_p1;
wire   [63:0] ireg_fu_709_p1;
wire   [10:0] exp_tmp_fu_725_p4;
wire   [51:0] trunc_ln554_fu_739_p1;
wire   [52:0] p_Result_10_fu_743_p3;
wire   [53:0] zext_ln558_fu_751_p1;
wire   [0:0] p_Result_9_fu_717_p3;
wire   [53:0] man_V_1_fu_755_p2;
wire   [62:0] trunc_ln544_fu_713_p1;
wire   [11:0] zext_ln455_fu_735_p1;
wire   [11:0] F2_fu_775_p2;
wire   [11:0] add_ln570_fu_787_p2;
wire   [11:0] sub_ln570_fu_793_p2;
wire   [6:0] tmp_8_fu_817_p4;
wire  signed [31:0] sext_ln570_fu_833_p1;
wire   [53:0] zext_ln575_fu_841_p1;
wire   [53:0] ashr_ln575_fu_845_p2;
wire   [31:0] bitcast_ln724_fu_854_p1;
wire   [0:0] tmp_7_fu_857_p3;
wire   [0:0] icmp_ln574_fu_836_p2;
wire   [31:0] trunc_ln575_fu_850_p1;
wire   [31:0] select_ln577_fu_865_p3;
wire   [31:0] shl_ln593_fu_881_p2;
wire   [0:0] xor_ln560_fu_893_p2;
wire   [0:0] and_ln571_fu_898_p2;
wire   [31:0] select_ln592_fu_886_p3;
wire   [0:0] or_ln571_fu_910_p2;
wire   [0:0] xor_ln571_fu_914_p2;
wire   [0:0] and_ln570_fu_920_p2;
wire   [31:0] select_ln574_fu_873_p3;
wire   [31:0] select_ln571_fu_903_p3;
wire   [31:0] select_ln570_fu_925_p3;
wire   [31:0] add_ln813_fu_933_p2;
wire   [31:0] grp_fu_949_p2;
reg    grp_fu_949_ap_start;
wire    grp_fu_949_ap_done;
wire    ap_CS_fsm_state69;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [68:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
reg    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
reg    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
reg    ap_ST_fsm_state68_blk;
reg    ap_ST_fsm_state69_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_user_V_U_apdone_blk;
wire   [0:0] in_stream_TUSER_int_regslice;
wire    regslice_both_in_stream_V_user_V_U_vld_out;
wire    regslice_both_in_stream_V_user_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    regslice_both_in_stream_V_id_V_U_apdone_blk;
wire   [0:0] in_stream_TID_int_regslice;
wire    regslice_both_in_stream_V_id_V_U_vld_out;
wire    regslice_both_in_stream_V_id_V_U_ack_in;
wire    regslice_both_in_stream_V_dest_V_U_apdone_blk;
wire   [0:0] in_stream_TDEST_int_regslice;
wire    regslice_both_in_stream_V_dest_V_U_vld_out;
wire    regslice_both_in_stream_V_dest_V_U_ack_in;
wire    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_user_V_U_apdone_blk;
wire    regslice_both_out_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_user_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    regslice_both_out_stream_V_id_V_U_apdone_blk;
wire    regslice_both_out_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_id_V_U_vld_out;
wire    regslice_both_out_stream_V_dest_V_U_apdone_blk;
wire    regslice_both_out_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 69'd1;
#0 grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_start_reg = 1'b0;
#0 grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_start_reg = 1'b0;
#0 grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_start_reg = 1'b0;
#0 grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_start_reg = 1'b0;
#0 grp_conv_layer01234_fused_fu_273_ap_start_reg = 1'b0;
#0 grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_start_reg = 1'b0;
end

ecg_denoiser_input_buf_V_RAM_1P_LUTRAM_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 180 ),
    .AddressWidth( 8 ))
input_buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_buf_V_address0),
    .ce0(input_buf_V_ce0),
    .we0(input_buf_V_we0),
    .d0(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_d0),
    .q0(input_buf_V_q0)
);

ecg_denoiser_input_buf_V_RAM_1P_LUTRAM_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 180 ),
    .AddressWidth( 8 ))
input_buf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_buf_V_1_address0),
    .ce0(input_buf_V_1_ce0),
    .we0(input_buf_V_1_we0),
    .d0(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_1_d0),
    .q0(input_buf_V_1_q0)
);

ecg_denoiser_input_buf_V_RAM_1P_LUTRAM_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 180 ),
    .AddressWidth( 8 ))
norm_buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(norm_buf_V_address0),
    .ce0(norm_buf_V_ce0),
    .we0(norm_buf_V_we0),
    .d0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_d0),
    .q0(norm_buf_V_q0)
);

ecg_denoiser_input_buf_V_RAM_1P_LUTRAM_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 180 ),
    .AddressWidth( 8 ))
norm_buf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(norm_buf_V_1_address0),
    .ce0(norm_buf_V_1_ce0),
    .we0(norm_buf_V_1_we0),
    .d0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_1_d0),
    .q0(norm_buf_V_1_q0)
);

ecg_denoiser_buf41210_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 360 ),
    .AddressWidth( 9 ))
buf41210_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buf41210_address0),
    .ce0(buf41210_ce0),
    .we0(buf41210_we0),
    .d0(grp_conv_layer01234_fused_fu_273_out_r_d0),
    .q0(buf41210_q0)
);

ecg_denoiser_ecg_denoiser_Pipeline_READ_INPUT grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_start),
    .ap_done(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_done),
    .ap_idle(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_idle),
    .ap_ready(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .input_buf_V_1_address0(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_1_address0),
    .input_buf_V_1_ce0(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_1_ce0),
    .input_buf_V_1_we0(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_1_we0),
    .input_buf_V_1_d0(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_1_d0),
    .input_buf_V_address0(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_address0),
    .input_buf_V_ce0(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_ce0),
    .input_buf_V_we0(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_we0),
    .input_buf_V_d0(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_d0),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TUSER(in_stream_TUSER_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice),
    .in_stream_TID(in_stream_TID_int_regslice),
    .in_stream_TDEST(in_stream_TDEST_int_regslice)
);

ecg_denoiser_ecg_denoiser_Pipeline_ZNORM_MEAN grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_start),
    .ap_done(grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_done),
    .ap_idle(grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_idle),
    .ap_ready(grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_ready),
    .input_buf_V_address0(grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_input_buf_V_address0),
    .input_buf_V_ce0(grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_input_buf_V_ce0),
    .input_buf_V_q0(input_buf_V_q0),
    .input_buf_V_1_address0(grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_input_buf_V_1_address0),
    .input_buf_V_1_ce0(grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_input_buf_V_1_ce0),
    .input_buf_V_1_q0(input_buf_V_1_q0),
    .mean_acc_V_out(grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_mean_acc_V_out),
    .mean_acc_V_out_ap_vld(grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_mean_acc_V_out_ap_vld)
);

ecg_denoiser_ecg_denoiser_Pipeline_ZNORM_VAR grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_start),
    .ap_done(grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_done),
    .ap_idle(grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_idle),
    .ap_ready(grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_ready),
    .input_buf_V_address0(grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_input_buf_V_address0),
    .input_buf_V_ce0(grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_input_buf_V_ce0),
    .input_buf_V_q0(input_buf_V_q0),
    .input_buf_V_1_address0(grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_input_buf_V_1_address0),
    .input_buf_V_1_ce0(grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_input_buf_V_1_ce0),
    .input_buf_V_1_q0(input_buf_V_1_q0),
    .mean_fx_V(mean_fx_V_reg_972),
    .var_acc_V_2_out(grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_var_acc_V_2_out),
    .var_acc_V_2_out_ap_vld(grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_var_acc_V_2_out_ap_vld)
);

ecg_denoiser_ecg_denoiser_Pipeline_ZNORM_APPLY grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_start),
    .ap_done(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_done),
    .ap_idle(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_idle),
    .ap_ready(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_ready),
    .norm_buf_V_1_address0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_1_address0),
    .norm_buf_V_1_ce0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_1_ce0),
    .norm_buf_V_1_we0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_1_we0),
    .norm_buf_V_1_d0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_1_d0),
    .norm_buf_V_address0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_address0),
    .norm_buf_V_ce0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_ce0),
    .norm_buf_V_we0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_we0),
    .norm_buf_V_d0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_d0),
    .input_buf_V_address0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_input_buf_V_address0),
    .input_buf_V_ce0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_input_buf_V_ce0),
    .input_buf_V_q0(input_buf_V_q0),
    .input_buf_V_1_address0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_input_buf_V_1_address0),
    .input_buf_V_1_ce0(grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_input_buf_V_1_ce0),
    .input_buf_V_1_q0(input_buf_V_1_q0),
    .rhs(mean_fx_V_reg_972),
    .sext_ln272(inv_std_fx_V_reg_1090)
);

ecg_denoiser_conv_layer01234_fused grp_conv_layer01234_fused_fu_273(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv_layer01234_fused_fu_273_ap_start),
    .ap_done(grp_conv_layer01234_fused_fu_273_ap_done),
    .ap_idle(grp_conv_layer01234_fused_fu_273_ap_idle),
    .ap_ready(grp_conv_layer01234_fused_fu_273_ap_ready),
    .in_0_address0(grp_conv_layer01234_fused_fu_273_in_0_address0),
    .in_0_ce0(grp_conv_layer01234_fused_fu_273_in_0_ce0),
    .in_0_q0(norm_buf_V_q0),
    .in_1_address0(grp_conv_layer01234_fused_fu_273_in_1_address0),
    .in_1_ce0(grp_conv_layer01234_fused_fu_273_in_1_ce0),
    .in_1_q0(norm_buf_V_1_q0),
    .out_r_address0(grp_conv_layer01234_fused_fu_273_out_r_address0),
    .out_r_ce0(grp_conv_layer01234_fused_fu_273_out_r_ce0),
    .out_r_we0(grp_conv_layer01234_fused_fu_273_out_r_we0),
    .out_r_d0(grp_conv_layer01234_fused_fu_273_out_r_d0)
);

ecg_denoiser_ecg_denoiser_Pipeline_WRITE_OUTPUT grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_start),
    .ap_done(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_done),
    .ap_idle(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_idle),
    .ap_ready(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_ready),
    .out_stream_TREADY(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TREADY),
    .buf41210_address0(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_buf41210_address0),
    .buf41210_ce0(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_buf41210_ce0),
    .buf41210_q0(buf41210_q0),
    .out_stream_TDATA(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TDATA),
    .out_stream_TVALID(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TVALID),
    .out_stream_TKEEP(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TKEEP),
    .out_stream_TSTRB(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TSTRB),
    .out_stream_TUSER(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TUSER),
    .out_stream_TLAST(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TLAST),
    .out_stream_TID(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TID),
    .out_stream_TDEST(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TDEST)
);

ecg_denoiser_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U149(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(d_assign_reg_1034),
    .ce(1'b1),
    .dout(grp_fu_317_p1)
);

ecg_denoiser_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U150(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(var_fx_f_reg_1022),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_320_p2)
);

ecg_denoiser_fsqrt_32ns_32ns_32_10_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsqrt_32ns_32ns_32_10_no_dsp_1_U151(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(32'd0),
    .din1(var_safe_reg_1029),
    .ce(1'b1),
    .dout(grp_fu_325_p2)
);

ecg_denoiser_mul_48s_9ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 48 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 56 ))
mul_48s_9ns_56_1_1_U152(
    .din0(grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_mean_acc_V_out),
    .din1(r_V_fu_337_p1),
    .dout(r_V_fu_337_p2)
);

ecg_denoiser_mul_48s_9ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 48 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 56 ))
mul_48s_9ns_56_1_1_U153(
    .din0(grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_var_acc_V_2_out),
    .din1(r_V_3_fu_361_p1),
    .dout(r_V_3_fu_361_p2)
);

ecg_denoiser_sdiv_34ns_32s_32_38_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 38 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_34ns_32s_32_38_seq_1_U154(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_949_ap_start),
    .done(grp_fu_949_ap_done),
    .din0(34'd4294967296),
    .din1(std_fx_V_reg_1080),
    .ce(1'b1),
    .dout(grp_fu_949_p2)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TUSER),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_user_V_U_ack_in),
    .data_out(in_stream_TUSER_int_regslice),
    .vld_out(regslice_both_in_stream_V_user_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_user_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TID),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_id_V_U_ack_in),
    .data_out(in_stream_TID_int_regslice),
    .vld_out(regslice_both_in_stream_V_id_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_id_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDEST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_dest_V_U_ack_in),
    .data_out(in_stream_TDEST_int_regslice),
    .vld_out(regslice_both_in_stream_V_dest_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_dest_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TDATA),
    .vld_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TKEEP),
    .vld_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TSTRB),
    .vld_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TUSER),
    .vld_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_user_V_U_ack_in_dummy),
    .data_out(out_stream_TUSER),
    .vld_out(regslice_both_out_stream_V_user_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_user_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TLAST),
    .vld_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TID),
    .vld_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_id_V_U_ack_in_dummy),
    .data_out(out_stream_TID),
    .vld_out(regslice_both_out_stream_V_id_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_id_V_U_apdone_blk)
);

ecg_denoiser_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TDEST),
    .vld_in(grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_dest_V_U_ack_in_dummy),
    .data_out(out_stream_TDEST),
    .vld_out(regslice_both_out_stream_V_dest_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv_layer01234_fused_fu_273_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state65)) begin
            grp_conv_layer01234_fused_fu_273_ap_start_reg <= 1'b1;
        end else if ((grp_conv_layer01234_fused_fu_273_ap_ready == 1'b1)) begin
            grp_conv_layer01234_fused_fu_273_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_start_reg <= 1'b1;
        end else if ((grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_ready == 1'b1)) begin
            grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state67)) begin
            grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_start_reg <= 1'b1;
        end else if ((grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_ready == 1'b1)) begin
            grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state63)) begin
            grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_start_reg <= 1'b1;
        end else if ((grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_ready == 1'b1)) begin
            grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_start_reg <= 1'b1;
        end else if ((grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_ready == 1'b1)) begin
            grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_start_reg <= 1'b1;
        end else if ((grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_ready == 1'b1)) begin
            grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        d_assign_reg_1034 <= grp_fu_325_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_ln1090_reg_991 <= icmp_ln1090_fu_385_p2;
        icmp_ln1113_reg_1012 <= icmp_ln1113_fu_527_p2;
        or_ln_reg_1007[0] <= or_ln_fu_519_p3[0];
        sub_ln1099_reg_1001 <= sub_ln1099_fu_419_p2;
        tmp_V_2_reg_996 <= tmp_V_2_fu_395_p3;
        trunc_ln1098_reg_1017 <= trunc_ln1098_fu_533_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        icmp_ln560_reg_1045 <= icmp_ln560_fu_769_p2;
        icmp_ln570_reg_1052 <= icmp_ln570_fu_781_p2;
        icmp_ln571_reg_1063 <= icmp_ln571_fu_807_p2;
        icmp_ln592_reg_1075 <= icmp_ln592_fu_827_p2;
        man_V_2_reg_1040 <= man_V_2_fu_761_p3;
        sh_amt_reg_1057 <= sh_amt_fu_799_p3;
        trunc_ln572_reg_1069 <= trunc_ln572_fu_813_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state63)) begin
        inv_std_fx_V_reg_1090 <= inv_std_fx_V_fu_955_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mean_fx_V_reg_972 <= {{r_V_fu_337_p2[55:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_Result_6_reg_985 <= r_V_3_fu_361_p2[32'd55];
        var_fx_reg_978 <= {{r_V_3_fu_361_p2[55:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        std_fx_V_reg_1080 <= std_fx_V_fu_939_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        var_fx_f_reg_1022 <= var_fx_f_fu_654_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        var_safe_reg_1029 <= var_safe_fu_702_p3;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

always @ (*) begin
    if ((grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

always @ (*) begin
    if ((grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_done == 1'b0)) begin
        ap_ST_fsm_state64_blk = 1'b1;
    end else begin
        ap_ST_fsm_state64_blk = 1'b0;
    end
end

assign ap_ST_fsm_state65_blk = 1'b0;

always @ (*) begin
    if ((grp_conv_layer01234_fused_fu_273_ap_done == 1'b0)) begin
        ap_ST_fsm_state66_blk = 1'b1;
    end else begin
        ap_ST_fsm_state66_blk = 1'b0;
    end
end

assign ap_ST_fsm_state67_blk = 1'b0;

always @ (*) begin
    if ((grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_done == 1'b0)) begin
        ap_ST_fsm_state68_blk = 1'b1;
    end else begin
        ap_ST_fsm_state68_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state69_blk = 1'b1;
    end else begin
        ap_ST_fsm_state69_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state69) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state69) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state68)) begin
        buf41210_address0 = grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_buf41210_address0;
    end else if ((1'b1 == ap_CS_fsm_state66)) begin
        buf41210_address0 = grp_conv_layer01234_fused_fu_273_out_r_address0;
    end else begin
        buf41210_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state68)) begin
        buf41210_ce0 = grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_buf41210_ce0;
    end else if ((1'b1 == ap_CS_fsm_state66)) begin
        buf41210_ce0 = grp_conv_layer01234_fused_fu_273_out_r_ce0;
    end else begin
        buf41210_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        buf41210_we0 = grp_conv_layer01234_fused_fu_273_out_r_we0;
    end else begin
        buf41210_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_949_ap_start = 1'b1;
    end else begin
        grp_fu_949_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        input_buf_V_1_address0 = grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_input_buf_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        input_buf_V_1_address0 = grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_input_buf_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        input_buf_V_1_address0 = grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_input_buf_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_buf_V_1_address0 = grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_1_address0;
    end else begin
        input_buf_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        input_buf_V_1_ce0 = grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_input_buf_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        input_buf_V_1_ce0 = grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_input_buf_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        input_buf_V_1_ce0 = grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_input_buf_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_buf_V_1_ce0 = grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_1_ce0;
    end else begin
        input_buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_buf_V_1_we0 = grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_1_we0;
    end else begin
        input_buf_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        input_buf_V_address0 = grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_input_buf_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        input_buf_V_address0 = grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_input_buf_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        input_buf_V_address0 = grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_input_buf_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_buf_V_address0 = grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_address0;
    end else begin
        input_buf_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        input_buf_V_ce0 = grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_input_buf_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        input_buf_V_ce0 = grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_input_buf_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        input_buf_V_ce0 = grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_input_buf_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_buf_V_ce0 = grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_ce0;
    end else begin
        input_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_buf_V_we0 = grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_input_buf_V_we0;
    end else begin
        input_buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        norm_buf_V_1_address0 = grp_conv_layer01234_fused_fu_273_in_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state64)) begin
        norm_buf_V_1_address0 = grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_1_address0;
    end else begin
        norm_buf_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        norm_buf_V_1_ce0 = grp_conv_layer01234_fused_fu_273_in_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state64)) begin
        norm_buf_V_1_ce0 = grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_1_ce0;
    end else begin
        norm_buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        norm_buf_V_1_we0 = grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_1_we0;
    end else begin
        norm_buf_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        norm_buf_V_address0 = grp_conv_layer01234_fused_fu_273_in_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state64)) begin
        norm_buf_V_address0 = grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_address0;
    end else begin
        norm_buf_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        norm_buf_V_ce0 = grp_conv_layer01234_fused_fu_273_in_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state64)) begin
        norm_buf_V_ce0 = grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_ce0;
    end else begin
        norm_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        norm_buf_V_we0 = grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_norm_buf_V_we0;
    end else begin
        norm_buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            if (((grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state64))) begin
                ap_NS_fsm = ap_ST_fsm_state65;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state64;
            end
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            if (((grp_conv_layer01234_fused_fu_273_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state66))) begin
                ap_NS_fsm = ap_ST_fsm_state67;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state66;
            end
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            if (((grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state68))) begin
                ap_NS_fsm = ap_ST_fsm_state69;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state68;
            end
        end
        ap_ST_fsm_state69 : begin
            if (((1'b1 == ap_CS_fsm_state69) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state69;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_fu_775_p2 = (12'd1075 - zext_ln455_fu_735_p1);

assign LD_fu_646_p1 = p_Result_8_fu_634_p5[31:0];

assign a_fu_479_p2 = (icmp_ln1102_fu_473_p2 & icmp_ln1101_fu_441_p2);

assign add_ln1113_fu_540_p2 = ($signed(sub_ln1099_reg_1001) + $signed(32'd4294967271));

assign add_ln1124_fu_621_p2 = (sub_ln1119_fu_616_p2 + select_ln1098_fu_608_p3);

assign add_ln570_fu_787_p2 = ($signed(F2_fu_775_p2) + $signed(12'd4080));

assign add_ln813_fu_933_p2 = (select_ln570_fu_925_p3 + 32'd6);

assign and_ln1104_fu_507_p2 = (xor_ln1104_fu_493_p2 & p_Result_1_fu_499_p3);

assign and_ln267_fu_696_p2 = (or_ln267_fu_690_p2 & grp_fu_320_p2);

assign and_ln570_fu_920_p2 = (xor_ln571_fu_914_p2 & icmp_ln570_reg_1052);

assign and_ln571_fu_898_p2 = (xor_ln560_fu_893_p2 & icmp_ln571_reg_1063);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state63 = ap_CS_fsm[32'd62];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state66 = ap_CS_fsm[32'd65];

assign ap_CS_fsm_state67 = ap_CS_fsm[32'd66];

assign ap_CS_fsm_state68 = ap_CS_fsm[32'd67];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ashr_ln575_fu_845_p2 = $signed(man_V_2_reg_1040) >>> zext_ln575_fu_841_p1;

assign bitcast_ln267_fu_661_p1 = var_fx_f_reg_1022;

assign bitcast_ln724_fu_854_p1 = d_assign_reg_1034;

assign bitcast_ln766_fu_650_p1 = LD_fu_646_p1;

assign exp_tmp_fu_725_p4 = {{ireg_fu_709_p1[62:52]}};

assign grp_conv_layer01234_fused_fu_273_ap_start = grp_conv_layer01234_fused_fu_273_ap_start_reg;

assign grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_start = grp_ecg_denoiser_Pipeline_READ_INPUT_fu_228_ap_start_reg;

assign grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_start = grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_ap_start_reg;

assign grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state68);

assign grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_start = grp_ecg_denoiser_Pipeline_ZNORM_APPLY_fu_263_ap_start_reg;

assign grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_start = grp_ecg_denoiser_Pipeline_ZNORM_MEAN_fu_248_ap_start_reg;

assign grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_start = grp_ecg_denoiser_Pipeline_ZNORM_VAR_fu_255_ap_start_reg;

assign icmp_ln1090_fu_385_p2 = ((var_fx_reg_978 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln1101_fu_441_p2 = (($signed(tmp_fu_431_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1102_fu_473_p2 = ((p_Result_s_fu_467_p2 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln1113_fu_527_p2 = (($signed(lsb_index_fu_425_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln267_1_fu_684_p2 = ((trunc_ln267_fu_674_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln267_fu_678_p2 = ((tmp_4_fu_664_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln560_fu_769_p2 = ((trunc_ln544_fu_713_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln570_fu_781_p2 = (($signed(F2_fu_775_p2) > $signed(12'd16)) ? 1'b1 : 1'b0);

assign icmp_ln571_fu_807_p2 = ((F2_fu_775_p2 == 12'd16) ? 1'b1 : 1'b0);

assign icmp_ln574_fu_836_p2 = ((sh_amt_reg_1057 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln592_fu_827_p2 = ((tmp_8_fu_817_p4 == 7'd0) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign inv_std_fx_V_fu_955_p1 = grp_fu_949_p2[31:0];

assign ireg_fu_709_p1 = grp_fu_317_p1;


always @ (p_Result_7_fu_401_p4) begin
    if (p_Result_7_fu_401_p4[0] == 1'b1) begin
        l_fu_411_p3 = 32'd0;
    end else if (p_Result_7_fu_401_p4[1] == 1'b1) begin
        l_fu_411_p3 = 32'd1;
    end else if (p_Result_7_fu_401_p4[2] == 1'b1) begin
        l_fu_411_p3 = 32'd2;
    end else if (p_Result_7_fu_401_p4[3] == 1'b1) begin
        l_fu_411_p3 = 32'd3;
    end else if (p_Result_7_fu_401_p4[4] == 1'b1) begin
        l_fu_411_p3 = 32'd4;
    end else if (p_Result_7_fu_401_p4[5] == 1'b1) begin
        l_fu_411_p3 = 32'd5;
    end else if (p_Result_7_fu_401_p4[6] == 1'b1) begin
        l_fu_411_p3 = 32'd6;
    end else if (p_Result_7_fu_401_p4[7] == 1'b1) begin
        l_fu_411_p3 = 32'd7;
    end else if (p_Result_7_fu_401_p4[8] == 1'b1) begin
        l_fu_411_p3 = 32'd8;
    end else if (p_Result_7_fu_401_p4[9] == 1'b1) begin
        l_fu_411_p3 = 32'd9;
    end else if (p_Result_7_fu_401_p4[10] == 1'b1) begin
        l_fu_411_p3 = 32'd10;
    end else if (p_Result_7_fu_401_p4[11] == 1'b1) begin
        l_fu_411_p3 = 32'd11;
    end else if (p_Result_7_fu_401_p4[12] == 1'b1) begin
        l_fu_411_p3 = 32'd12;
    end else if (p_Result_7_fu_401_p4[13] == 1'b1) begin
        l_fu_411_p3 = 32'd13;
    end else if (p_Result_7_fu_401_p4[14] == 1'b1) begin
        l_fu_411_p3 = 32'd14;
    end else if (p_Result_7_fu_401_p4[15] == 1'b1) begin
        l_fu_411_p3 = 32'd15;
    end else if (p_Result_7_fu_401_p4[16] == 1'b1) begin
        l_fu_411_p3 = 32'd16;
    end else if (p_Result_7_fu_401_p4[17] == 1'b1) begin
        l_fu_411_p3 = 32'd17;
    end else if (p_Result_7_fu_401_p4[18] == 1'b1) begin
        l_fu_411_p3 = 32'd18;
    end else if (p_Result_7_fu_401_p4[19] == 1'b1) begin
        l_fu_411_p3 = 32'd19;
    end else if (p_Result_7_fu_401_p4[20] == 1'b1) begin
        l_fu_411_p3 = 32'd20;
    end else if (p_Result_7_fu_401_p4[21] == 1'b1) begin
        l_fu_411_p3 = 32'd21;
    end else if (p_Result_7_fu_401_p4[22] == 1'b1) begin
        l_fu_411_p3 = 32'd22;
    end else if (p_Result_7_fu_401_p4[23] == 1'b1) begin
        l_fu_411_p3 = 32'd23;
    end else if (p_Result_7_fu_401_p4[24] == 1'b1) begin
        l_fu_411_p3 = 32'd24;
    end else if (p_Result_7_fu_401_p4[25] == 1'b1) begin
        l_fu_411_p3 = 32'd25;
    end else if (p_Result_7_fu_401_p4[26] == 1'b1) begin
        l_fu_411_p3 = 32'd26;
    end else if (p_Result_7_fu_401_p4[27] == 1'b1) begin
        l_fu_411_p3 = 32'd27;
    end else if (p_Result_7_fu_401_p4[28] == 1'b1) begin
        l_fu_411_p3 = 32'd28;
    end else if (p_Result_7_fu_401_p4[29] == 1'b1) begin
        l_fu_411_p3 = 32'd29;
    end else if (p_Result_7_fu_401_p4[30] == 1'b1) begin
        l_fu_411_p3 = 32'd30;
    end else if (p_Result_7_fu_401_p4[31] == 1'b1) begin
        l_fu_411_p3 = 32'd31;
    end else begin
        l_fu_411_p3 = 32'd32;
    end
end

assign lsb_index_fu_425_p2 = ($signed(sub_ln1099_fu_419_p2) + $signed(32'd4294967272));

assign lshr_ln1102_fu_461_p2 = 32'd4294967295 >> zext_ln1102_fu_457_p1;

assign lshr_ln1113_fu_549_p2 = zext_ln1112_fu_537_p1 >> zext_ln1113_fu_545_p1;

assign m_2_fu_570_p3 = ((icmp_ln1113_reg_1012[0:0] == 1'b1) ? lshr_ln1113_fu_549_p2 : shl_ln1114_fu_564_p2);

assign m_3_fu_580_p2 = (m_2_fu_570_p3 + zext_ln1116_fu_577_p1);

assign m_4_fu_586_p4 = {{m_3_fu_580_p2[63:1]}};

assign man_V_1_fu_755_p2 = (54'd0 - zext_ln558_fu_751_p1);

assign man_V_2_fu_761_p3 = ((p_Result_9_fu_717_p3[0:0] == 1'b1) ? man_V_1_fu_755_p2 : zext_ln558_fu_751_p1);

assign or_ln1104_fu_513_p2 = (and_ln1104_fu_507_p2 | a_fu_479_p2);

assign or_ln267_fu_690_p2 = (icmp_ln267_fu_678_p2 | icmp_ln267_1_fu_684_p2);

assign or_ln571_fu_910_p2 = (icmp_ln571_reg_1063 | icmp_ln560_reg_1045);

assign or_ln_fu_519_p3 = {{1'd0}, {or_ln1104_fu_513_p2}};

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign out_stream_TVALID_int_regslice = grp_ecg_denoiser_Pipeline_WRITE_OUTPUT_fu_298_out_stream_TVALID;

assign p_Result_10_fu_743_p3 = {{1'd1}, {trunc_ln554_fu_739_p1}};

assign p_Result_1_fu_499_p3 = tmp_V_2_fu_395_p3[lsb_index_fu_425_p2];

assign p_Result_2_fu_600_p3 = m_3_fu_580_p2[32'd25];

integer ap_tvar_int_0;

always @ (tmp_V_2_fu_395_p3) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            p_Result_7_fu_401_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_7_fu_401_p4[ap_tvar_int_0] = tmp_V_2_fu_395_p3[31 - ap_tvar_int_0];
        end
    end
end

assign p_Result_8_fu_634_p5 = {{zext_ln1117_fu_596_p1[63:32]}, {tmp_5_fu_627_p3}, {zext_ln1117_fu_596_p1[22:0]}};

assign p_Result_9_fu_717_p3 = ireg_fu_709_p1[32'd63];

assign p_Result_s_fu_467_p2 = (tmp_V_2_fu_395_p3 & lshr_ln1102_fu_461_p2);

assign r_V_3_fu_361_p1 = 56'd182;

assign r_V_fu_337_p1 = 56'd182;

assign select_ln1098_fu_608_p3 = ((p_Result_2_fu_600_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln570_fu_925_p3 = ((and_ln570_fu_920_p2[0:0] == 1'b1) ? select_ln574_fu_873_p3 : select_ln571_fu_903_p3);

assign select_ln571_fu_903_p3 = ((and_ln571_fu_898_p2[0:0] == 1'b1) ? trunc_ln572_reg_1069 : select_ln592_fu_886_p3);

assign select_ln574_fu_873_p3 = ((icmp_ln574_fu_836_p2[0:0] == 1'b1) ? trunc_ln575_fu_850_p1 : select_ln577_fu_865_p3);

assign select_ln577_fu_865_p3 = ((tmp_7_fu_857_p3[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign select_ln592_fu_886_p3 = ((icmp_ln592_reg_1075[0:0] == 1'b1) ? shl_ln593_fu_881_p2 : 32'd0);

assign sext_ln570_fu_833_p1 = sh_amt_reg_1057;

assign sh_amt_fu_799_p3 = ((icmp_ln570_fu_781_p2[0:0] == 1'b1) ? add_ln570_fu_787_p2 : sub_ln570_fu_793_p2);

assign shl_ln1114_fu_564_p2 = zext_ln1112_fu_537_p1 << zext_ln1114_fu_560_p1;

assign shl_ln593_fu_881_p2 = trunc_ln572_reg_1069 << sext_ln570_fu_833_p1;

assign std_fx_V_fu_939_p3 = ((icmp_ln560_reg_1045[0:0] == 1'b1) ? 32'd6 : add_ln813_fu_933_p2);

assign sub_ln1099_fu_419_p2 = (32'd32 - l_fu_411_p3);

assign sub_ln1102_fu_451_p2 = ($signed(5'd25) - $signed(trunc_ln1102_fu_447_p1));

assign sub_ln1114_fu_555_p2 = (32'd25 - sub_ln1099_reg_1001);

assign sub_ln1119_fu_616_p2 = (8'd16 - trunc_ln1098_reg_1017);

assign sub_ln570_fu_793_p2 = (12'd16 - F2_fu_775_p2);

assign tmp_1_fu_485_p3 = lsb_index_fu_425_p2[32'd31];

assign tmp_4_fu_664_p4 = {{bitcast_ln267_fu_661_p1[30:23]}};

assign tmp_5_fu_627_p3 = {{p_Result_6_reg_985}, {add_ln1124_fu_621_p2}};

assign tmp_7_fu_857_p3 = bitcast_ln724_fu_854_p1[32'd31];

assign tmp_8_fu_817_p4 = {{sh_amt_fu_799_p3[11:5]}};

assign tmp_V_2_fu_395_p3 = ((p_Result_6_reg_985[0:0] == 1'b1) ? tmp_V_fu_390_p2 : var_fx_reg_978);

assign tmp_V_fu_390_p2 = (32'd0 - var_fx_reg_978);

assign tmp_fu_431_p4 = {{lsb_index_fu_425_p2[31:1]}};

assign trunc_ln1098_fu_533_p1 = l_fu_411_p3[7:0];

assign trunc_ln1102_fu_447_p1 = sub_ln1099_fu_419_p2[4:0];

assign trunc_ln267_fu_674_p1 = bitcast_ln267_fu_661_p1[22:0];

assign trunc_ln544_fu_713_p1 = ireg_fu_709_p1[62:0];

assign trunc_ln554_fu_739_p1 = ireg_fu_709_p1[51:0];

assign trunc_ln572_fu_813_p1 = man_V_2_fu_761_p3[31:0];

assign trunc_ln575_fu_850_p1 = ashr_ln575_fu_845_p2[31:0];

assign var_fx_f_fu_654_p3 = ((icmp_ln1090_reg_991[0:0] == 1'b1) ? 32'd0 : bitcast_ln766_fu_650_p1);

assign var_safe_fu_702_p3 = ((and_ln267_fu_696_p2[0:0] == 1'b1) ? var_fx_f_reg_1022 : 32'd841731191);

assign xor_ln1104_fu_493_p2 = (tmp_1_fu_485_p3 ^ 1'd1);

assign xor_ln560_fu_893_p2 = (icmp_ln560_reg_1045 ^ 1'd1);

assign xor_ln571_fu_914_p2 = (or_ln571_fu_910_p2 ^ 1'd1);

assign zext_ln1102_fu_457_p1 = sub_ln1102_fu_451_p2;

assign zext_ln1112_fu_537_p1 = tmp_V_2_reg_996;

assign zext_ln1113_fu_545_p1 = add_ln1113_fu_540_p2;

assign zext_ln1114_fu_560_p1 = sub_ln1114_fu_555_p2;

assign zext_ln1116_fu_577_p1 = or_ln_reg_1007;

assign zext_ln1117_fu_596_p1 = m_4_fu_586_p4;

assign zext_ln455_fu_735_p1 = exp_tmp_fu_725_p4;

assign zext_ln558_fu_751_p1 = p_Result_10_fu_743_p3;

assign zext_ln575_fu_841_p1 = $unsigned(sext_ln570_fu_833_p1);

always @ (posedge ap_clk) begin
    or_ln_reg_1007[1] <= 1'b0;
end


reg find_kernel_block = 0;
// synthesis translate_off
`include "ecg_denoiser_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //ecg_denoiser

