-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_denoiser_conv_layer01234_fused_Pipeline_L2_IC_L2_K is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln143 : IN STD_LOGIC_VECTOR (24 downto 0);
    sext_ln142 : IN STD_LOGIC_VECTOR (24 downto 0);
    oc_base_1 : IN STD_LOGIC_VECTOR (5 downto 0);
    zext_ln837_4 : IN STD_LOGIC_VECTOR (12 downto 0);
    win12_V_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    win12_V_1_ce0 : OUT STD_LOGIC;
    win12_V_1_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    win12_V_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    win12_V_2_ce0 : OUT STD_LOGIC;
    win12_V_2_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    win12_V_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    win12_V_3_ce0 : OUT STD_LOGIC;
    win12_V_3_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    phi_ln818_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    phi_ln818_2_out_ap_vld : OUT STD_LOGIC;
    phi_ln818_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    phi_ln818_3_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ecg_denoiser_conv_layer01234_fused_Pipeline_L2_IC_L2_K is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv10_280 : STD_LOGIC_VECTOR (9 downto 0) := "1010000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln145_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal denoiser_w_L2_W_V_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal denoiser_w_L2_W_V_ce0 : STD_LOGIC;
    signal denoiser_w_L2_W_V_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal denoiser_w_L2_W_V_address1 : STD_LOGIC_VECTOR (15 downto 0);
    signal denoiser_w_L2_W_V_ce1 : STD_LOGIC;
    signal denoiser_w_L2_W_V_q1 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln837_4_cast_fu_248_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln837_4_cast_reg_738 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln145_reg_743 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln145_reg_743_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln145_fu_320_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln145_reg_747 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln145_1_fu_328_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln145_1_reg_753 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_V_fu_472_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_V_reg_785 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_9_fu_510_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal r_V_9_reg_790 : STD_LOGIC_VECTOR (61 downto 0);
    signal r_V_10_fu_528_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal r_V_10_reg_796 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln145_fu_336_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln837_14_fu_450_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln837_15_fu_467_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_ln818_3_fu_110 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal phi_ln818_2_fu_114 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_fu_118 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln142_cast_fu_240_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal lhs_V_fu_122 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln143_cast_fu_244_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal k_fu_126 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln147_fu_343_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_k_load : STD_LOGIC_VECTOR (2 downto 0);
    signal ic_1_fu_130 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_ic_1_load : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten25_fu_134 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln145_1_fu_296_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten25_load : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln147_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln145_fu_308_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_367_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln837_9_fu_376_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_380_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_13_fu_393_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln837_11_fu_402_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln837_10_fu_389_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln837_fu_364_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln837_3_fu_412_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln837_fu_406_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln837_13_fu_441_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln837_4_fu_444_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_shl3_fu_421_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln837_12_fu_417_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln837_5_fu_455_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln837_6_fu_461_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_V_fu_472_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_V_fu_472_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_V_fu_472_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_fu_487_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal shl_ln838_s_fu_494_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal r_V_9_fu_510_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln1270_fu_502_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal shl_ln838_2_fu_516_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal r_V_10_fu_528_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal trunc_ln147_fu_548_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln1347_5_fu_552_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln147_fu_560_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_3_fu_540_p3 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1347_fu_563_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln1347_fu_572_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal trunc_ln147_1_fu_596_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln1347_7_fu_600_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln147_1_fu_608_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_V_3_fu_588_p3 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1347_2_fu_611_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln1347_2_fu_620_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln147_1_fu_566_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln147_2_fu_614_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_denoiser_mux_53_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_denoiser_mul_23s_40s_62_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (22 downto 0);
        din1 : IN STD_LOGIC_VECTOR (39 downto 0);
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component ecg_denoiser_conv_layer01234_fused_Pipeline_L2_IC_L2_K_denoiser_w_L2_W_V_ROM_NP_LUTRAM_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        address1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component ecg_denoiser_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    denoiser_w_L2_W_V_U : component ecg_denoiser_conv_layer01234_fused_Pipeline_L2_IC_L2_K_denoiser_w_L2_W_V_ROM_NP_LUTRAM_1R
    generic map (
        DataWidth => 15,
        AddressRange => 40960,
        AddressWidth => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => denoiser_w_L2_W_V_address0,
        ce0 => denoiser_w_L2_W_V_ce0,
        q0 => denoiser_w_L2_W_V_q0,
        address1 => denoiser_w_L2_W_V_address1,
        ce1 => denoiser_w_L2_W_V_ce1,
        q1 => denoiser_w_L2_W_V_q1);

    mux_53_32_1_1_U60 : component ecg_denoiser_mux_53_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_0,
        din1 => ap_const_lv32_0,
        din2 => x_V_fu_472_p3,
        din3 => x_V_fu_472_p4,
        din4 => x_V_fu_472_p5,
        din5 => select_ln145_reg_747,
        dout => x_V_fu_472_p7);

    mul_23s_40s_62_1_1_U61 : component ecg_denoiser_mul_23s_40s_62_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 23,
        din1_WIDTH => 40,
        dout_WIDTH => 62)
    port map (
        din0 => shl_ln838_s_fu_494_p3,
        din1 => r_V_9_fu_510_p1,
        dout => r_V_9_fu_510_p2);

    mul_23s_40s_62_1_1_U62 : component ecg_denoiser_mul_23s_40s_62_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 23,
        din1_WIDTH => 40,
        dout_WIDTH => 62)
    port map (
        din0 => shl_ln838_2_fu_516_p3,
        din1 => r_V_10_fu_528_p1,
        dout => r_V_10_fu_528_p2);

    flow_control_loop_pipe_sequential_init_U : component ecg_denoiser_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ic_1_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln145_fu_290_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    ic_1_fu_130 <= select_ln145_1_fu_328_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ic_1_fu_130 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten25_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln145_fu_290_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten25_fu_134 <= add_ln145_1_fu_296_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten25_fu_134 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    k_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln145_fu_290_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_126 <= add_ln147_fu_343_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_126 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_V_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    lhs_V_fu_122 <= sext_ln143_cast_fu_244_p1;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    lhs_V_fu_122 <= add_ln1347_2_fu_620_p2(71 downto 24);
                end if;
            end if; 
        end if;
    end process;

    lhs_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    lhs_fu_118 <= sext_ln142_cast_fu_240_p1;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    lhs_fu_118 <= add_ln1347_fu_572_p2(71 downto 24);
                end if;
            end if; 
        end if;
    end process;

    phi_ln818_2_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    phi_ln818_2_fu_114 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    phi_ln818_2_fu_114 <= add_ln147_1_fu_566_p2(63 downto 32);
                end if;
            end if; 
        end if;
    end process;

    phi_ln818_3_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    phi_ln818_3_fu_110 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    phi_ln818_3_fu_110 <= add_ln147_2_fu_614_p2(63 downto 32);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln145_reg_743 <= icmp_ln145_fu_290_p2;
                icmp_ln145_reg_743_pp0_iter1_reg <= icmp_ln145_reg_743;
                x_V_reg_785 <= x_V_fu_472_p7;
                    zext_ln837_4_cast_reg_738(12 downto 0) <= zext_ln837_4_cast_fu_248_p1(12 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                r_V_10_reg_796 <= r_V_10_fu_528_p2;
                r_V_9_reg_790 <= r_V_9_fu_510_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln145_fu_290_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln145_1_reg_753 <= select_ln145_1_fu_328_p3;
                select_ln145_reg_747 <= select_ln145_fu_320_p3;
            end if;
        end if;
    end process;
    zext_ln837_4_cast_reg_738(13) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1347_2_fu_620_p2 <= std_logic_vector(unsigned(lhs_V_3_fu_588_p3) + unsigned(sext_ln1347_2_fu_611_p1));
    add_ln1347_fu_572_p2 <= std_logic_vector(unsigned(lhs_3_fu_540_p3) + unsigned(sext_ln1347_fu_563_p1));
    add_ln145_1_fu_296_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten25_load) + unsigned(ap_const_lv10_1));
    add_ln145_fu_308_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ic_1_load) + unsigned(ap_const_lv8_1));
    add_ln147_1_fu_566_p2 <= std_logic_vector(unsigned(sext_ln1347_5_fu_552_p3) + unsigned(sext_ln147_fu_560_p1));
    add_ln147_2_fu_614_p2 <= std_logic_vector(unsigned(sext_ln1347_7_fu_600_p3) + unsigned(sext_ln147_1_fu_608_p1));
    add_ln147_fu_343_p2 <= std_logic_vector(unsigned(select_ln145_fu_320_p3) + unsigned(ap_const_lv3_1));
    add_ln837_3_fu_412_p2 <= std_logic_vector(unsigned(zext_ln837_4_cast_reg_738) + unsigned(zext_ln837_fu_364_p1));
    add_ln837_4_fu_444_p2 <= std_logic_vector(unsigned(add_ln837_fu_406_p2) + unsigned(zext_ln837_13_fu_441_p1));
    add_ln837_5_fu_455_p2 <= std_logic_vector(unsigned(p_shl3_fu_421_p3) + unsigned(zext_ln837_12_fu_417_p1));
    add_ln837_6_fu_461_p2 <= std_logic_vector(unsigned(add_ln837_5_fu_455_p2) + unsigned(zext_ln837_13_fu_441_p1));
    add_ln837_fu_406_p2 <= std_logic_vector(unsigned(zext_ln837_11_fu_402_p1) + unsigned(zext_ln837_10_fu_389_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln145_fu_290_p2)
    begin
        if (((icmp_ln145_fu_290_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_ic_1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, ic_1_fu_130)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_ic_1_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_ic_1_load <= ic_1_fu_130;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten25_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten25_fu_134)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten25_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten25_load <= indvar_flatten25_fu_134;
        end if; 
    end process;


    ap_sig_allocacmp_k_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_126)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_k_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_k_load <= k_fu_126;
        end if; 
    end process;

    denoiser_w_L2_W_V_address0 <= zext_ln837_15_fu_467_p1(16 - 1 downto 0);
    denoiser_w_L2_W_V_address1 <= zext_ln837_14_fu_450_p1(16 - 1 downto 0);

    denoiser_w_L2_W_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            denoiser_w_L2_W_V_ce0 <= ap_const_logic_1;
        else 
            denoiser_w_L2_W_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    denoiser_w_L2_W_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            denoiser_w_L2_W_V_ce1 <= ap_const_logic_1;
        else 
            denoiser_w_L2_W_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln145_fu_290_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten25_load = ap_const_lv10_280) else "0";
    icmp_ln147_fu_314_p2 <= "1" when (ap_sig_allocacmp_k_load = ap_const_lv3_5) else "0";
    lhs_3_fu_540_p3 <= (lhs_fu_118 & ap_const_lv24_0);
    lhs_V_3_fu_588_p3 <= (lhs_V_fu_122 & ap_const_lv24_0);
    p_shl3_fu_421_p3 <= (add_ln837_3_fu_412_p2 & ap_const_lv2_0);
    phi_ln818_2_out <= phi_ln818_2_fu_114;

    phi_ln818_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln145_reg_743_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln145_reg_743_pp0_iter1_reg = ap_const_lv1_1))) then 
            phi_ln818_2_out_ap_vld <= ap_const_logic_1;
        else 
            phi_ln818_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    phi_ln818_3_out <= phi_ln818_3_fu_110;

    phi_ln818_3_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln145_reg_743_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln145_reg_743_pp0_iter1_reg = ap_const_lv1_1))) then 
            phi_ln818_3_out_ap_vld <= ap_const_logic_1;
        else 
            phi_ln818_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    r_V_10_fu_528_p1 <= sext_ln1270_fu_502_p1(40 - 1 downto 0);
    r_V_9_fu_510_p1 <= sext_ln1270_fu_502_p1(40 - 1 downto 0);
    r_V_fu_487_p3 <= (x_V_reg_785 & ap_const_lv8_0);
    select_ln145_1_fu_328_p3 <= 
        add_ln145_fu_308_p2 when (icmp_ln147_fu_314_p2(0) = '1') else 
        ap_sig_allocacmp_ic_1_load;
    select_ln145_fu_320_p3 <= 
        ap_const_lv3_0 when (icmp_ln147_fu_314_p2(0) = '1') else 
        ap_sig_allocacmp_k_load;
        sext_ln1270_fu_502_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_fu_487_p3),62));

        sext_ln1347_2_fu_611_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_10_reg_796),72));

    sext_ln1347_5_fu_552_p3 <= (trunc_ln147_fu_548_p1 & ap_const_lv24_0);
    sext_ln1347_7_fu_600_p3 <= (trunc_ln147_1_fu_596_p1 & ap_const_lv24_0);
        sext_ln1347_fu_563_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_9_reg_790),72));

        sext_ln142_cast_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln142),48));

        sext_ln143_cast_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln143),48));

        sext_ln147_1_fu_608_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_10_reg_796),64));

        sext_ln147_fu_560_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_9_reg_790),64));

    shl_ln838_2_fu_516_p3 <= (denoiser_w_L2_W_V_q0 & ap_const_lv8_0);
    shl_ln838_s_fu_494_p3 <= (denoiser_w_L2_W_V_q1 & ap_const_lv8_0);
    tmp_13_fu_393_p4 <= ((tmp_fu_367_p4 & select_ln145_1_reg_753) & ap_const_lv2_0);
    tmp_fu_367_p4 <= oc_base_1(5 downto 1);
    tmp_s_fu_380_p4 <= ((ap_const_lv1_0 & zext_ln837_9_fu_376_p1) & select_ln145_1_reg_753);
    trunc_ln147_1_fu_596_p1 <= lhs_V_fu_122(40 - 1 downto 0);
    trunc_ln147_fu_548_p1 <= lhs_fu_118(40 - 1 downto 0);
    win12_V_1_address0 <= zext_ln145_fu_336_p1(7 - 1 downto 0);

    win12_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win12_V_1_ce0 <= ap_const_logic_1;
        else 
            win12_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    win12_V_2_address0 <= zext_ln145_fu_336_p1(7 - 1 downto 0);

    win12_V_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win12_V_2_ce0 <= ap_const_logic_1;
        else 
            win12_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    win12_V_3_address0 <= zext_ln145_fu_336_p1(7 - 1 downto 0);

    win12_V_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            win12_V_3_ce0 <= ap_const_logic_1;
        else 
            win12_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_V_fu_472_p3 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win12_V_1_q0),32));
    x_V_fu_472_p4 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win12_V_2_q0),32));
    x_V_fu_472_p5 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(win12_V_3_q0),32));
    zext_ln145_fu_336_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln145_1_fu_328_p3),64));
    zext_ln837_10_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_380_p4),16));
    zext_ln837_11_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_393_p4),16));
    zext_ln837_12_fu_417_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln837_3_fu_412_p2),16));
    zext_ln837_13_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln145_reg_747),16));
    zext_ln837_14_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln837_4_fu_444_p2),64));
    zext_ln837_15_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln837_6_fu_461_p2),64));
    zext_ln837_4_cast_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln837_4),14));
    zext_ln837_9_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_367_p4),6));
    zext_ln837_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln145_1_reg_753),14));
end behav;
