// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ecg_classifier_ecg_classifier_Pipeline_L2_IC_L2_K (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln178,
        sext_ln177,
        win01_V_2_address0,
        win01_V_2_ce0,
        win01_V_2_q0,
        win01_V_3_address0,
        win01_V_3_ce0,
        win01_V_3_q0,
        win01_V_4_address0,
        win01_V_4_ce0,
        win01_V_4_q0,
        win01_V_5_address0,
        win01_V_5_ce0,
        win01_V_5_q0,
        win01_V_6_address0,
        win01_V_6_ce0,
        win01_V_6_q0,
        win01_V_7_address0,
        win01_V_7_ce0,
        win01_V_7_q0,
        win01_V_8_address0,
        win01_V_8_ce0,
        win01_V_8_q0,
        win01_V_9_address0,
        win01_V_9_ce0,
        win01_V_9_q0,
        oc_base_1,
        zext_ln837_9,
        phi_ln818_3_out,
        phi_ln818_3_out_ap_vld,
        phi_ln818_4_out,
        phi_ln818_4_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [25:0] sext_ln178;
input  [25:0] sext_ln177;
output  [4:0] win01_V_2_address0;
output   win01_V_2_ce0;
input  [30:0] win01_V_2_q0;
output  [4:0] win01_V_3_address0;
output   win01_V_3_ce0;
input  [30:0] win01_V_3_q0;
output  [4:0] win01_V_4_address0;
output   win01_V_4_ce0;
input  [30:0] win01_V_4_q0;
output  [4:0] win01_V_5_address0;
output   win01_V_5_ce0;
input  [30:0] win01_V_5_q0;
output  [4:0] win01_V_6_address0;
output   win01_V_6_ce0;
input  [30:0] win01_V_6_q0;
output  [4:0] win01_V_7_address0;
output   win01_V_7_ce0;
input  [30:0] win01_V_7_q0;
output  [4:0] win01_V_8_address0;
output   win01_V_8_ce0;
input  [30:0] win01_V_8_q0;
output  [4:0] win01_V_9_address0;
output   win01_V_9_ce0;
input  [30:0] win01_V_9_q0;
input  [6:0] oc_base_1;
input  [12:0] zext_ln837_9;
output  [15:0] phi_ln818_3_out;
output   phi_ln818_3_out_ap_vld;
output  [15:0] phi_ln818_4_out;
output   phi_ln818_4_out_ap_vld;

reg ap_idle;
reg[4:0] win01_V_2_address0;
reg win01_V_2_ce0;
reg[4:0] win01_V_3_address0;
reg win01_V_3_ce0;
reg[4:0] win01_V_4_address0;
reg win01_V_4_ce0;
reg[4:0] win01_V_5_address0;
reg win01_V_5_ce0;
reg[4:0] win01_V_6_address0;
reg win01_V_6_ce0;
reg[4:0] win01_V_7_address0;
reg win01_V_7_ce0;
reg[4:0] win01_V_8_address0;
reg win01_V_8_ce0;
reg[4:0] win01_V_9_address0;
reg win01_V_9_ce0;
reg phi_ln818_3_out_ap_vld;
reg phi_ln818_4_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln180_fu_450_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [15:0] clf_w_L2_W_V_address0;
reg    clf_w_L2_W_V_ce0;
wire   [2:0] clf_w_L2_W_V_q0;
wire   [15:0] clf_w_L2_W_V_address1;
reg    clf_w_L2_W_V_ce1;
wire   [2:0] clf_w_L2_W_V_q1;
wire    ap_block_pp0_stage0_11001;
wire   [13:0] zext_ln837_9_cast_fu_391_p1;
reg   [13:0] zext_ln837_9_cast_reg_1029;
reg   [4:0] tmp_s_reg_1034;
wire   [0:0] empty_fu_446_p1;
reg   [0:0] empty_reg_1039;
reg   [0:0] empty_reg_1039_pp0_iter1_reg;
reg   [0:0] icmp_ln180_reg_1048;
reg   [0:0] icmp_ln180_reg_1048_pp0_iter1_reg;
reg   [0:0] icmp_ln180_reg_1048_pp0_iter2_reg;
wire   [0:0] icmp_ln182_fu_471_p2;
reg   [0:0] icmp_ln182_reg_1052;
reg   [0:0] icmp_ln182_reg_1052_pp0_iter1_reg;
wire   [2:0] select_ln180_fu_477_p3;
reg   [2:0] select_ln180_reg_1061;
reg   [2:0] select_ln180_reg_1061_pp0_iter1_reg;
wire   [6:0] select_ln180_1_fu_485_p3;
reg   [6:0] select_ln180_1_reg_1067;
reg   [4:0] p_mid1_reg_1074;
wire   [0:0] empty_63_fu_503_p1;
reg   [0:0] empty_63_reg_1079;
reg   [0:0] empty_63_reg_1079_pp0_iter1_reg;
wire   [30:0] tmp_16_fu_765_p7;
reg   [30:0] tmp_16_reg_1178;
reg   [2:0] clf_w_L2_W_V_load_reg_1183;
reg   [2:0] clf_w_L2_W_V_load_1_reg_1188;
wire  signed [61:0] r_V_fu_802_p2;
reg  signed [61:0] r_V_reg_1193;
wire   [55:0] trunc_ln182_1_fu_808_p1;
reg   [55:0] trunc_ln182_1_reg_1198;
wire  signed [61:0] r_V_8_fu_823_p2;
reg  signed [61:0] r_V_8_reg_1203;
wire   [55:0] trunc_ln182_3_fu_829_p1;
reg   [55:0] trunc_ln182_3_reg_1208;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] p_cast39_fu_528_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] p_cast39_mid1_fu_598_p1;
wire   [63:0] zext_ln837_17_fu_618_p1;
wire   [63:0] zext_ln837_18_fu_635_p1;
reg   [15:0] phi_ln818_4_fu_124;
wire    ap_loop_init;
reg   [15:0] phi_ln818_3_fu_128;
reg   [47:0] lhs_V_fu_132;
wire  signed [47:0] sext_ln177_cast_fu_383_p1;
reg   [47:0] lhs_V_8_fu_136;
wire  signed [47:0] sext_ln178_cast_fu_387_p1;
reg   [2:0] k_fu_140;
wire   [2:0] add_ln184_fu_507_p2;
reg   [2:0] ap_sig_allocacmp_k_load;
reg   [6:0] ic_fu_144;
reg   [6:0] ap_sig_allocacmp_ic_2;
reg   [8:0] indvar_flatten39_fu_148;
wire   [8:0] add_ln180_1_fu_456_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten39_load;
wire    ap_block_pp0_stage0_01001;
wire   [6:0] add_ln180_fu_465_p2;
wire   [5:0] tmp_fu_542_p4;
wire   [12:0] tmp_4_fu_551_p3;
wire   [14:0] tmp_5_fu_562_p4;
wire   [15:0] zext_ln837_14_fu_571_p1;
wire   [15:0] zext_ln837_13_fu_558_p1;
wire   [13:0] zext_ln837_fu_539_p1;
wire   [13:0] add_ln837_7_fu_581_p2;
wire   [15:0] add_ln837_fu_575_p2;
wire   [15:0] zext_ln837_16_fu_609_p1;
wire   [15:0] add_ln837_8_fu_612_p2;
wire   [15:0] p_shl2_fu_590_p3;
wire   [15:0] zext_ln837_15_fu_586_p1;
wire   [15:0] add_ln837_9_fu_623_p2;
wire   [15:0] add_ln837_10_fu_629_p2;
wire   [30:0] tmp_6_mid1_fu_685_p4;
wire   [30:0] tmp_6_fu_640_p4;
wire   [30:0] tmp_10_mid1_fu_701_p4;
wire   [30:0] tmp_10_fu_649_p4;
wire   [30:0] tmp_11_mid1_fu_717_p4;
wire   [30:0] tmp_11_fu_658_p4;
wire   [30:0] tmp_12_mid1_fu_733_p4;
wire   [30:0] tmp_12_fu_667_p4;
wire   [30:0] tmp_13_mid1_fu_749_p4;
wire   [30:0] tmp_13_fu_676_p4;
wire   [30:0] tmp_16_fu_765_p1;
wire   [30:0] tmp_16_fu_765_p2;
wire   [30:0] tmp_16_fu_765_p3;
wire   [30:0] tmp_16_fu_765_p4;
wire   [30:0] tmp_16_fu_765_p5;
wire   [38:0] tmp_17_fu_780_p3;
wire  signed [22:0] shl_ln838_8_fu_787_p3;
wire   [38:0] r_V_fu_802_p1;
wire   [61:0] zext_ln1270_fu_794_p1;
wire  signed [22:0] shl_ln838_s_fu_812_p3;
wire   [38:0] r_V_8_fu_823_p1;
wire   [31:0] trunc_ln182_fu_847_p1;
wire   [55:0] sext_ln1347_8_fu_851_p3;
wire   [71:0] lhs_V_9_fu_839_p3;
wire  signed [71:0] sext_ln1347_fu_859_p1;
wire   [71:0] add_ln1347_fu_867_p2;
wire   [31:0] trunc_ln182_2_fu_891_p1;
wire   [55:0] sext_ln1347_s_fu_895_p3;
wire   [71:0] lhs_V_10_fu_883_p3;
wire  signed [71:0] sext_ln1347_4_fu_903_p1;
wire   [71:0] add_ln1347_3_fu_911_p2;
wire   [55:0] add_ln182_fu_862_p2;
wire   [55:0] add_ln182_1_fu_906_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_252;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

ecg_classifier_ecg_classifier_Pipeline_L2_IC_L2_K_clf_w_L2_W_V_ROM_AUTO_1R #(
    .DataWidth( 3 ),
    .AddressRange( 40960 ),
    .AddressWidth( 16 ))
clf_w_L2_W_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(clf_w_L2_W_V_address0),
    .ce0(clf_w_L2_W_V_ce0),
    .q0(clf_w_L2_W_V_q0),
    .address1(clf_w_L2_W_V_address1),
    .ce1(clf_w_L2_W_V_ce1),
    .q1(clf_w_L2_W_V_q1)
);

ecg_classifier_mux_21_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 31 ))
mux_21_31_1_1_U58(
    .din0(31'd0),
    .din1(31'd0),
    .din2(empty_reg_1039_pp0_iter1_reg),
    .dout(tmp_6_fu_640_p4)
);

ecg_classifier_mux_21_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 31 ))
mux_21_31_1_1_U59(
    .din0(win01_V_2_q0),
    .din1(win01_V_3_q0),
    .din2(empty_reg_1039_pp0_iter1_reg),
    .dout(tmp_10_fu_649_p4)
);

ecg_classifier_mux_21_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 31 ))
mux_21_31_1_1_U60(
    .din0(win01_V_4_q0),
    .din1(win01_V_5_q0),
    .din2(empty_reg_1039_pp0_iter1_reg),
    .dout(tmp_11_fu_658_p4)
);

ecg_classifier_mux_21_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 31 ))
mux_21_31_1_1_U61(
    .din0(win01_V_6_q0),
    .din1(win01_V_7_q0),
    .din2(empty_reg_1039_pp0_iter1_reg),
    .dout(tmp_12_fu_667_p4)
);

ecg_classifier_mux_21_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 31 ))
mux_21_31_1_1_U62(
    .din0(win01_V_8_q0),
    .din1(win01_V_9_q0),
    .din2(empty_reg_1039_pp0_iter1_reg),
    .dout(tmp_13_fu_676_p4)
);

ecg_classifier_mux_21_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 31 ))
mux_21_31_1_1_U63(
    .din0(31'd0),
    .din1(31'd0),
    .din2(empty_63_reg_1079_pp0_iter1_reg),
    .dout(tmp_6_mid1_fu_685_p4)
);

ecg_classifier_mux_21_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 31 ))
mux_21_31_1_1_U64(
    .din0(win01_V_2_q0),
    .din1(win01_V_3_q0),
    .din2(empty_63_reg_1079_pp0_iter1_reg),
    .dout(tmp_10_mid1_fu_701_p4)
);

ecg_classifier_mux_21_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 31 ))
mux_21_31_1_1_U65(
    .din0(win01_V_4_q0),
    .din1(win01_V_5_q0),
    .din2(empty_63_reg_1079_pp0_iter1_reg),
    .dout(tmp_11_mid1_fu_717_p4)
);

ecg_classifier_mux_21_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 31 ))
mux_21_31_1_1_U66(
    .din0(win01_V_6_q0),
    .din1(win01_V_7_q0),
    .din2(empty_63_reg_1079_pp0_iter1_reg),
    .dout(tmp_12_mid1_fu_733_p4)
);

ecg_classifier_mux_21_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 31 ))
mux_21_31_1_1_U67(
    .din0(win01_V_8_q0),
    .din1(win01_V_9_q0),
    .din2(empty_63_reg_1079_pp0_iter1_reg),
    .dout(tmp_13_mid1_fu_749_p4)
);

ecg_classifier_mux_53_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 31 ),
    .din3_WIDTH( 31 ),
    .din4_WIDTH( 31 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 31 ))
mux_53_31_1_1_U68(
    .din0(tmp_16_fu_765_p1),
    .din1(tmp_16_fu_765_p2),
    .din2(tmp_16_fu_765_p3),
    .din3(tmp_16_fu_765_p4),
    .din4(tmp_16_fu_765_p5),
    .din5(select_ln180_reg_1061_pp0_iter1_reg),
    .dout(tmp_16_fu_765_p7)
);

ecg_classifier_mul_23s_39ns_62_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 39 ),
    .dout_WIDTH( 62 ))
mul_23s_39ns_62_1_1_U69(
    .din0(shl_ln838_8_fu_787_p3),
    .din1(r_V_fu_802_p1),
    .dout(r_V_fu_802_p2)
);

ecg_classifier_mul_23s_39ns_62_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 39 ),
    .dout_WIDTH( 62 ))
mul_23s_39ns_62_1_1_U70(
    .din0(shl_ln838_s_fu_812_p3),
    .din1(r_V_8_fu_823_p1),
    .dout(r_V_8_fu_823_p2)
);

ecg_classifier_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln180_fu_450_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ic_fu_144 <= select_ln180_1_fu_485_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ic_fu_144 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln180_fu_450_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten39_fu_148 <= add_ln180_1_fu_456_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten39_fu_148 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln180_fu_450_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_140 <= add_ln184_fu_507_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_140 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_V_8_fu_136 <= sext_ln178_cast_fu_387_p1;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            lhs_V_8_fu_136 <= {{add_ln1347_3_fu_911_p2[71:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_V_fu_132 <= sext_ln177_cast_fu_383_p1;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            lhs_V_fu_132 <= {{add_ln1347_fu_867_p2[71:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            phi_ln818_3_fu_128 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            phi_ln818_3_fu_128 <= {{add_ln182_fu_862_p2[55:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            phi_ln818_4_fu_124 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            phi_ln818_4_fu_124 <= {{add_ln182_1_fu_906_p2[55:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_63_reg_1079_pp0_iter1_reg <= empty_63_reg_1079;
        empty_reg_1039 <= empty_fu_446_p1;
        empty_reg_1039_pp0_iter1_reg <= empty_reg_1039;
        icmp_ln180_reg_1048 <= icmp_ln180_fu_450_p2;
        icmp_ln180_reg_1048_pp0_iter1_reg <= icmp_ln180_reg_1048;
        icmp_ln182_reg_1052_pp0_iter1_reg <= icmp_ln182_reg_1052;
        select_ln180_reg_1061_pp0_iter1_reg <= select_ln180_reg_1061;
        tmp_s_reg_1034 <= {{ap_sig_allocacmp_ic_2[5:1]}};
        zext_ln837_9_cast_reg_1029[12 : 0] <= zext_ln837_9_cast_fu_391_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln180_reg_1048_pp0_iter2_reg <= icmp_ln180_reg_1048_pp0_iter1_reg;
        r_V_8_reg_1203 <= r_V_8_fu_823_p2;
        r_V_reg_1193 <= r_V_fu_802_p2;
        trunc_ln182_1_reg_1198 <= trunc_ln182_1_fu_808_p1;
        trunc_ln182_3_reg_1208 <= trunc_ln182_3_fu_829_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln180_reg_1048_pp0_iter1_reg == 1'd0))) begin
        clf_w_L2_W_V_load_1_reg_1188 <= clf_w_L2_W_V_q0;
        clf_w_L2_W_V_load_reg_1183 <= clf_w_L2_W_V_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln180_fu_450_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_63_reg_1079 <= empty_63_fu_503_p1;
        icmp_ln182_reg_1052 <= icmp_ln182_fu_471_p2;
        p_mid1_reg_1074 <= {{add_ln180_fu_465_p2[5:1]}};
        select_ln180_1_reg_1067 <= select_ln180_1_fu_485_p3;
        select_ln180_reg_1061 <= select_ln180_fu_477_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln180_reg_1048_pp0_iter1_reg == 1'd0))) begin
        tmp_16_reg_1178 <= tmp_16_fu_765_p7;
    end
end

always @ (*) begin
    if (((icmp_ln180_fu_450_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln180_reg_1048_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ic_2 = 7'd0;
    end else begin
        ap_sig_allocacmp_ic_2 = ic_fu_144;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten39_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten39_load = indvar_flatten39_fu_148;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_load = 3'd0;
    end else begin
        ap_sig_allocacmp_k_load = k_fu_140;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        clf_w_L2_W_V_ce0 = 1'b1;
    end else begin
        clf_w_L2_W_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        clf_w_L2_W_V_ce1 = 1'b1;
    end else begin
        clf_w_L2_W_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln180_reg_1048_pp0_iter2_reg == 1'd1))) begin
        phi_ln818_3_out_ap_vld = 1'b1;
    end else begin
        phi_ln818_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln180_reg_1048_pp0_iter2_reg == 1'd1))) begin
        phi_ln818_4_out_ap_vld = 1'b1;
    end else begin
        phi_ln818_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_252)) begin
        if (((icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0))) begin
            win01_V_2_address0 = p_cast39_mid1_fu_598_p1;
        end else if ((icmp_ln182_reg_1052 == 1'd0)) begin
            win01_V_2_address0 = p_cast39_fu_528_p1;
        end else begin
            win01_V_2_address0 = 'bx;
        end
    end else begin
        win01_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd0)))) begin
        win01_V_2_ce0 = 1'b1;
    end else begin
        win01_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_252)) begin
        if (((icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0))) begin
            win01_V_3_address0 = p_cast39_mid1_fu_598_p1;
        end else if ((icmp_ln182_reg_1052 == 1'd0)) begin
            win01_V_3_address0 = p_cast39_fu_528_p1;
        end else begin
            win01_V_3_address0 = 'bx;
        end
    end else begin
        win01_V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd0)))) begin
        win01_V_3_ce0 = 1'b1;
    end else begin
        win01_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_252)) begin
        if (((icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0))) begin
            win01_V_4_address0 = p_cast39_mid1_fu_598_p1;
        end else if ((icmp_ln182_reg_1052 == 1'd0)) begin
            win01_V_4_address0 = p_cast39_fu_528_p1;
        end else begin
            win01_V_4_address0 = 'bx;
        end
    end else begin
        win01_V_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd0)))) begin
        win01_V_4_ce0 = 1'b1;
    end else begin
        win01_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_252)) begin
        if (((icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0))) begin
            win01_V_5_address0 = p_cast39_mid1_fu_598_p1;
        end else if ((icmp_ln182_reg_1052 == 1'd0)) begin
            win01_V_5_address0 = p_cast39_fu_528_p1;
        end else begin
            win01_V_5_address0 = 'bx;
        end
    end else begin
        win01_V_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd0)))) begin
        win01_V_5_ce0 = 1'b1;
    end else begin
        win01_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_252)) begin
        if (((icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0))) begin
            win01_V_6_address0 = p_cast39_mid1_fu_598_p1;
        end else if ((icmp_ln182_reg_1052 == 1'd0)) begin
            win01_V_6_address0 = p_cast39_fu_528_p1;
        end else begin
            win01_V_6_address0 = 'bx;
        end
    end else begin
        win01_V_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd0)))) begin
        win01_V_6_ce0 = 1'b1;
    end else begin
        win01_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_252)) begin
        if (((icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0))) begin
            win01_V_7_address0 = p_cast39_mid1_fu_598_p1;
        end else if ((icmp_ln182_reg_1052 == 1'd0)) begin
            win01_V_7_address0 = p_cast39_fu_528_p1;
        end else begin
            win01_V_7_address0 = 'bx;
        end
    end else begin
        win01_V_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd0)))) begin
        win01_V_7_ce0 = 1'b1;
    end else begin
        win01_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_252)) begin
        if (((icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0))) begin
            win01_V_8_address0 = p_cast39_mid1_fu_598_p1;
        end else if ((icmp_ln182_reg_1052 == 1'd0)) begin
            win01_V_8_address0 = p_cast39_fu_528_p1;
        end else begin
            win01_V_8_address0 = 'bx;
        end
    end else begin
        win01_V_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd0)))) begin
        win01_V_8_ce0 = 1'b1;
    end else begin
        win01_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_252)) begin
        if (((icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0))) begin
            win01_V_9_address0 = p_cast39_mid1_fu_598_p1;
        end else if ((icmp_ln182_reg_1052 == 1'd0)) begin
            win01_V_9_address0 = p_cast39_fu_528_p1;
        end else begin
            win01_V_9_address0 = 'bx;
        end
    end else begin
        win01_V_9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd1) & (icmp_ln180_reg_1048 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_reg_1052 == 1'd0)))) begin
        win01_V_9_ce0 = 1'b1;
    end else begin
        win01_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1347_3_fu_911_p2 = ($signed(lhs_V_10_fu_883_p3) + $signed(sext_ln1347_4_fu_903_p1));

assign add_ln1347_fu_867_p2 = ($signed(lhs_V_9_fu_839_p3) + $signed(sext_ln1347_fu_859_p1));

assign add_ln180_1_fu_456_p2 = (ap_sig_allocacmp_indvar_flatten39_load + 9'd1);

assign add_ln180_fu_465_p2 = (ap_sig_allocacmp_ic_2 + 7'd1);

assign add_ln182_1_fu_906_p2 = (sext_ln1347_s_fu_895_p3 + trunc_ln182_3_reg_1208);

assign add_ln182_fu_862_p2 = (sext_ln1347_8_fu_851_p3 + trunc_ln182_1_reg_1198);

assign add_ln184_fu_507_p2 = (select_ln180_fu_477_p3 + 3'd1);

assign add_ln837_10_fu_629_p2 = (add_ln837_9_fu_623_p2 + zext_ln837_16_fu_609_p1);

assign add_ln837_7_fu_581_p2 = (zext_ln837_9_cast_reg_1029 + zext_ln837_fu_539_p1);

assign add_ln837_8_fu_612_p2 = (add_ln837_fu_575_p2 + zext_ln837_16_fu_609_p1);

assign add_ln837_9_fu_623_p2 = (p_shl2_fu_590_p3 + zext_ln837_15_fu_586_p1);

assign add_ln837_fu_575_p2 = (zext_ln837_14_fu_571_p1 + zext_ln837_13_fu_558_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_252 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign clf_w_L2_W_V_address0 = zext_ln837_18_fu_635_p1;

assign clf_w_L2_W_V_address1 = zext_ln837_17_fu_618_p1;

assign empty_63_fu_503_p1 = add_ln180_fu_465_p2[0:0];

assign empty_fu_446_p1 = ap_sig_allocacmp_ic_2[0:0];

assign icmp_ln180_fu_450_p2 = ((ap_sig_allocacmp_indvar_flatten39_load == 9'd320) ? 1'b1 : 1'b0);

assign icmp_ln182_fu_471_p2 = ((ap_sig_allocacmp_k_load == 3'd5) ? 1'b1 : 1'b0);

assign lhs_V_10_fu_883_p3 = {{lhs_V_8_fu_136}, {24'd0}};

assign lhs_V_9_fu_839_p3 = {{lhs_V_fu_132}, {24'd0}};

assign p_cast39_fu_528_p1 = tmp_s_reg_1034;

assign p_cast39_mid1_fu_598_p1 = p_mid1_reg_1074;

assign p_shl2_fu_590_p3 = {{add_ln837_7_fu_581_p2}, {2'd0}};

assign phi_ln818_3_out = phi_ln818_3_fu_128;

assign phi_ln818_4_out = phi_ln818_4_fu_124;

assign r_V_8_fu_823_p1 = zext_ln1270_fu_794_p1;

assign r_V_fu_802_p1 = zext_ln1270_fu_794_p1;

assign select_ln180_1_fu_485_p3 = ((icmp_ln182_fu_471_p2[0:0] == 1'b1) ? add_ln180_fu_465_p2 : ap_sig_allocacmp_ic_2);

assign select_ln180_fu_477_p3 = ((icmp_ln182_fu_471_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_k_load);

assign sext_ln1347_4_fu_903_p1 = r_V_8_reg_1203;

assign sext_ln1347_8_fu_851_p3 = {{trunc_ln182_fu_847_p1}, {24'd0}};

assign sext_ln1347_fu_859_p1 = r_V_reg_1193;

assign sext_ln1347_s_fu_895_p3 = {{trunc_ln182_2_fu_891_p1}, {24'd0}};

assign sext_ln177_cast_fu_383_p1 = $signed(sext_ln177);

assign sext_ln178_cast_fu_387_p1 = $signed(sext_ln178);

assign shl_ln838_8_fu_787_p3 = {{clf_w_L2_W_V_load_reg_1183}, {20'd0}};

assign shl_ln838_s_fu_812_p3 = {{clf_w_L2_W_V_load_1_reg_1188}, {20'd0}};

assign tmp_16_fu_765_p1 = ((icmp_ln182_reg_1052_pp0_iter1_reg[0:0] == 1'b1) ? tmp_6_mid1_fu_685_p4 : tmp_6_fu_640_p4);

assign tmp_16_fu_765_p2 = ((icmp_ln182_reg_1052_pp0_iter1_reg[0:0] == 1'b1) ? tmp_10_mid1_fu_701_p4 : tmp_10_fu_649_p4);

assign tmp_16_fu_765_p3 = ((icmp_ln182_reg_1052_pp0_iter1_reg[0:0] == 1'b1) ? tmp_11_mid1_fu_717_p4 : tmp_11_fu_658_p4);

assign tmp_16_fu_765_p4 = ((icmp_ln182_reg_1052_pp0_iter1_reg[0:0] == 1'b1) ? tmp_12_mid1_fu_733_p4 : tmp_12_fu_667_p4);

assign tmp_16_fu_765_p5 = ((icmp_ln182_reg_1052_pp0_iter1_reg[0:0] == 1'b1) ? tmp_13_mid1_fu_749_p4 : tmp_13_fu_676_p4);

assign tmp_17_fu_780_p3 = {{tmp_16_reg_1178}, {8'd0}};

assign tmp_4_fu_551_p3 = {{tmp_fu_542_p4}, {select_ln180_1_reg_1067}};

assign tmp_5_fu_562_p4 = {{{tmp_fu_542_p4}, {select_ln180_1_reg_1067}}, {2'd0}};

assign tmp_fu_542_p4 = {{oc_base_1[6:1]}};

assign trunc_ln182_1_fu_808_p1 = r_V_fu_802_p2[55:0];

assign trunc_ln182_2_fu_891_p1 = lhs_V_8_fu_136[31:0];

assign trunc_ln182_3_fu_829_p1 = r_V_8_fu_823_p2[55:0];

assign trunc_ln182_fu_847_p1 = lhs_V_fu_132[31:0];

assign zext_ln1270_fu_794_p1 = tmp_17_fu_780_p3;

assign zext_ln837_13_fu_558_p1 = tmp_4_fu_551_p3;

assign zext_ln837_14_fu_571_p1 = tmp_5_fu_562_p4;

assign zext_ln837_15_fu_586_p1 = add_ln837_7_fu_581_p2;

assign zext_ln837_16_fu_609_p1 = select_ln180_reg_1061;

assign zext_ln837_17_fu_618_p1 = add_ln837_8_fu_612_p2;

assign zext_ln837_18_fu_635_p1 = add_ln837_10_fu_629_p2;

assign zext_ln837_9_cast_fu_391_p1 = zext_ln837_9;

assign zext_ln837_fu_539_p1 = select_ln180_1_reg_1067;

always @ (posedge ap_clk) begin
    zext_ln837_9_cast_reg_1029[13] <= 1'b0;
end

endmodule //ecg_classifier_ecg_classifier_Pipeline_L2_IC_L2_K
