// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ecg_classifier_ecg_classifier_Pipeline_READ_INPUT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        input_buf_V_1_address0,
        input_buf_V_1_ce0,
        input_buf_V_1_we0,
        input_buf_V_1_d0,
        input_buf_V_address0,
        input_buf_V_ce0,
        input_buf_V_we0,
        input_buf_V_d0,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
output  [6:0] input_buf_V_1_address0;
output   input_buf_V_1_ce0;
output   input_buf_V_1_we0;
output  [31:0] input_buf_V_1_d0;
output  [6:0] input_buf_V_address0;
output   input_buf_V_ce0;
output   input_buf_V_we0;
output  [31:0] input_buf_V_d0;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;

reg ap_idle;
reg input_buf_V_1_ce0;
reg input_buf_V_1_we0;
reg input_buf_V_ce0;
reg input_buf_V_we0;
reg in_stream_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln43_fu_124_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire   [63:0] zext_ln49_fu_152_p1;
reg   [7:0] t_fu_68;
wire   [7:0] add_ln43_fu_130_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_t_3;
wire   [0:0] trunc_ln49_fu_158_p1;
wire   [6:0] lshr_ln_fu_142_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_139;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

ecg_classifier_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln43_fu_124_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_139)) begin
        if ((icmp_ln43_fu_124_p2 == 1'd0)) begin
            t_fu_68 <= add_ln43_fu_130_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_68 <= 8'd0;
        end
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln43_fu_124_p2 == 1'd0) & (in_stream_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln43_fu_124_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln43_fu_124_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln43_fu_124_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln43_fu_124_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_t_3 = 8'd0;
    end else begin
        ap_sig_allocacmp_t_3 = t_fu_68;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_124_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln43_fu_124_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln43_fu_124_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln43_fu_124_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        input_buf_V_1_ce0 = 1'b1;
    end else begin
        input_buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln43_fu_124_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln49_fu_158_p1 == 1'd1) & (icmp_ln43_fu_124_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input_buf_V_1_we0 = 1'b1;
    end else begin
        input_buf_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln43_fu_124_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        input_buf_V_ce0 = 1'b1;
    end else begin
        input_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln43_fu_124_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln49_fu_158_p1 == 1'd0) & (icmp_ln43_fu_124_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input_buf_V_we0 = 1'b1;
    end else begin
        input_buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln43_fu_130_p2 = (ap_sig_allocacmp_t_3 + 8'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln43_fu_124_p2 == 1'd0) & (in_stream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_139 = (~((ap_start_int == 1'b0) | ((icmp_ln43_fu_124_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln43_fu_124_p2 = ((ap_sig_allocacmp_t_3 == 8'd187) ? 1'b1 : 1'b0);

assign input_buf_V_1_address0 = zext_ln49_fu_152_p1;

assign input_buf_V_1_d0 = in_stream_TDATA;

assign input_buf_V_address0 = zext_ln49_fu_152_p1;

assign input_buf_V_d0 = in_stream_TDATA;

assign lshr_ln_fu_142_p4 = {{ap_sig_allocacmp_t_3[7:1]}};

assign trunc_ln49_fu_158_p1 = ap_sig_allocacmp_t_3[0:0];

assign zext_ln49_fu_152_p1 = lshr_ln_fu_142_p4;

endmodule //ecg_classifier_ecg_classifier_Pipeline_READ_INPUT
